-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per GL journal header.
with source as (
    select * from {{ source('sage_x3', 'GACCENTRY') }}
),

cleaned as (

    select
        nullif(trim("NUM_0"), '') as journal_entry_number,
        nullif(trim("TYP_0"), '') as entry_type_code,
        nullif(trim("JOU_0"), '') as journal_code,
        nullif(trim("CPY_0"), '') as company_code,
        nullif(trim("FCY_0"), '') as site_code,
        nullif("ACCDAT_0", date '1753-01-01') as accounting_date,
        nullif(trim("CUR_0"), '') as currency_code,
        nullif(trim("DES_0"), '') as description,
        nullif(trim("VCRNUM_0"), '') as source_document_number,
        cast("STA_0" as bigint) as entry_status_code,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

)

select * from cleaned
