-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per item and site.
with source as (
    select * from {{ source('sage_x3', 'ITMFACILIT') }}
),

cleaned as (

    select
        nullif(trim("ITMREF_0"), '') as item_code,
        nullif(trim("STOFCY_0"), '') as site_code,
        cast("REOMODE_0" as bigint) as reorder_mode_code,
        cast("SAFSTO_0" as decimal(18, 4)) as safety_stock_qty,
        cast("REOMINQTY_0" as decimal(18, 4)) as reorder_min_qty,
        cast("REOMAXQTY_0" as decimal(18, 4)) as reorder_max_qty,
        cast("LTISUP_0" as bigint) as supplier_lead_time_days,
        nullif(trim("ABCCLS_0"), '') as abc_class,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

),

decoded_reorder_mode as (

    select
        base.*,
        menu.menu_label as reorder_mode

    from cleaned as base
    left join {{ ref('stg_sage_x3__aplstd') }} as menu
        on menu.menu_chapter = 861
        and menu.menu_code = base.reorder_mode_code
        and menu.language_code = 'ENG'

)

select * from decoded_reorder_mode
