-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per sales order line (quantity side).
with source as (
    select * from {{ source('sage_x3', 'SORDERQ') }}
),

cleaned as (

    select
        nullif(trim("SOHNUM_0"), '') as sales_order_number,
        cast("SOPLIN_0" as bigint) as sales_order_line_number,
        cast("SOQSEQ_0" as bigint) as sales_order_line_sequence,
        nullif(trim("ITMREF_0"), '') as item_code,
        nullif(trim("STOFCY_0"), '') as shipping_site_code,
        cast("QTY_0" as decimal(18, 4)) as ordered_qty,
        nullif("DEMDLVDAT_0", date '1753-01-01') as requested_delivery_date,
        cast("SHTQTY_0" as decimal(18, 4)) as shipped_qty,
        nullif(trim("UOM_0"), '') as unit_of_measure,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

)

select * from cleaned
