-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per sales representative.
with source as (
    select * from {{ source('sage_x3', 'REPRESENT') }}
),

cleaned as (

    select
        nullif(trim("REPNUM_0"), '') as rep_code,
        nullif(trim("REPNAM_0"), '') as rep_name,
        nullif(trim("FCY_0"), '') as site_code,
        cast("REPTYP_0" as bigint) as rep_type_code,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

)

select * from cleaned
