-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per customer return header.
with source as (
    select * from {{ source('sage_x3', 'SRETURN') }}
),

cleaned as (

    select
        nullif(trim("SRHNUM_0"), '') as return_number,
        nullif(trim("SRHFCY_0"), '') as site_code,
        nullif(trim("BPCNUM_0"), '') as customer_code,
        nullif("RTNDAT_0", date '1753-01-01') as return_date,
        nullif(trim("SOHNUM_0"), '') as sales_order_number,
        nullif(trim("SIVNUM_0"), '') as invoice_number,
        cast("RTNSTA_0" as bigint) as return_status_code,
        cast("RTNREN_0" as bigint) as return_reason_code,
        nullif(trim("CREUSR_0"), '') as created_by,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

),

decoded_return_status as (

    select
        base.*,
        menu.menu_label as return_status

    from cleaned as base
    left join {{ ref('stg_sage_x3__aplstd') }} as menu
        on menu.menu_chapter = 740
        and menu.menu_code = base.return_status_code
        and menu.language_code = 'ENG'

),

decoded_return_reason as (

    select
        base.*,
        menu.menu_label as return_reason

    from decoded_return_status as base
    left join {{ ref('stg_sage_x3__aplstd') }} as menu
        on menu.menu_chapter = 720
        and menu.menu_code = base.return_reason_code
        and menu.language_code = 'ENG'

)

select * from decoded_return_reason
