-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per goods receipt line.
with source as (
    select * from {{ source('sage_x3', 'PRECEIPTD') }}
),

cleaned as (

    select
        nullif(trim("PTHNUM_0"), '') as receipt_number,
        cast("PTDLIN_0" as bigint) as receipt_line_number,
        nullif(trim("POHNUM_0"), '') as purchase_order_number,
        cast("POPLIN_0" as bigint) as purchase_order_line_number,
        nullif(trim("ITMREF_0"), '') as item_code,
        nullif(trim("PTHFCY_0"), '') as receipt_site_code,
        cast("QTYUOM_0" as decimal(18, 4)) as received_qty,
        nullif("RCPDAT_0", date '1753-01-01') as receipt_date

    from source

)

select * from cleaned
