-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per stock movement (STOJOU.ROWID).
with source as (
    select * from {{ source('sage_x3', 'STOJOU') }}
),

cleaned as (

    select
        cast("ROWID" as bigint) as stock_movement_id,
        nullif(trim("ITMREF_0"), '') as item_code,
        nullif(trim("STOFCY_0"), '') as site_code,
        nullif("IPTDAT_0", date '1753-01-01') as movement_date,
        cast("TRSTYP_0" as bigint) as movement_type_code,
        cast("QTYSTU_0" as decimal(18, 4)) as movement_qty,
        nullif(trim("VCRNUM_0"), '') as document_number,
        nullif(trim("VCRTYP_0"), '') as document_type,
        nullif(trim("LOT_0"), '') as lot_code,
        nullif(trim("CREUSR_0"), '') as created_by,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

),

decoded_movement_type as (

    select
        base.*,
        menu.menu_label as movement_type

    from cleaned as base
    left join {{ ref('stg_sage_x3__aplstd') }} as menu
        on menu.menu_chapter = 700
        and menu.menu_code = base.movement_type_code
        and menu.language_code = 'ENG'

)

select * from decoded_movement_type
