-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per translated field value.
with source as (
    select * from {{ source('sage_x3', 'ATEXTRA') }}
),

cleaned as (

    select
        nullif(trim("CODFIC_0"), '') as table_code,
        nullif(trim("ZONE_0"), '') as field_code,
        nullif(trim("LANNUM_0"), '') as language_code,
        nullif(trim("IDENT1_0"), '') as key_1,
        nullif(trim("IDENT2_0"), '') as key_2,
        nullif(trim("TEXTE_0"), '') as translated_text

    from source

)

select * from cleaned
