-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per item, site, lot and location.
with source as (
    select * from {{ source('sage_x3', 'STOCK') }}
),

cleaned as (

    select
        nullif(trim("STOFCY_0"), '') as site_code,
        nullif(trim("ITMREF_0"), '') as item_code,
        nullif(trim("LOT_0"), '') as lot_code,
        nullif(trim("LOC_0"), '') as location_code,
        cast("QTYSTU_0" as decimal(18, 4)) as on_hand_qty,
        nullif(trim("STA_0"), '') as stock_status,
        nullif(trim("OWNER_0"), '') as owner_code,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

)

select * from cleaned
