-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per supplier invoice header.
with source as (
    select * from {{ source('sage_x3', 'PINVOICE') }}
),

cleaned as (

    select
        nullif(trim("NUM_0"), '') as supplier_invoice_number,
        nullif(trim("PIVTYP_0"), '') as invoice_type_code,
        nullif(trim("BPSNUM_0"), '') as supplier_code,
        nullif(trim("BPSINV_0"), '') as supplier_document_number,
        nullif("INVDAT_0", date '1753-01-01') as invoice_date,
        nullif("ACCDAT_0", date '1753-01-01') as accounting_date,
        nullif(trim("PIHFCY_0"), '') as site_code,
        nullif(trim("CUR_0"), '') as currency_code,
        cast("AMTNOTLIN_0" as decimal(18, 4)) as net_amount,
        cast("AMTTAXLIN_0" as decimal(18, 4)) as tax_amount,
        cast("AMTATILIN_0" as decimal(18, 4)) as gross_amount,
        cast("INVSTA_0" as bigint) as invoice_status_code,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

)

select * from cleaned
