-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per item.
with source as (
    select * from {{ source('sage_x3', 'ITMMASTER') }}
),

cleaned as (

    select
        nullif(trim("ITMREF_0"), '') as item_code,
        nullif(trim("ITMDES1_0"), '') as item_description,
        nullif(trim("ITMDES2_0"), '') as item_description_2,
        nullif(trim("TCLCOD_0"), '') as item_category_code,
        nullif(trim("TSICOD_0"), '') as statistical_group_1,
        nullif(trim("TSICOD_1"), '') as statistical_group_2,
        nullif(trim("TSICOD_2"), '') as statistical_group_3,
        nullif(trim("STU_0"), '') as stock_unit,
        cast("ITMSTA_0" as bigint) as item_status_code,
        cast("BASPRI_0" as decimal(18, 4)) as base_sales_price,
        cast("PURBASPRI_0" as decimal(18, 4)) as base_purchase_price,
        nullif(trim("EANCOD_0"), '') as ean_code,
        cast("ITMWEI_0" as decimal(18, 4)) as item_weight,
        nullif("CREDAT_0", date '1753-01-01') as created_date,
        nullif("UPDDAT_0", date '1753-01-01') as updated_date,
        nullif(trim("CREUSR_0"), '') as created_by,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

),

decoded_item_status as (

    select
        base.*,
        menu.menu_label as item_status

    from cleaned as base
    left join {{ ref('stg_sage_x3__aplstd') }} as menu
        on menu.menu_chapter = 20
        and menu.menu_code = base.item_status_code
        and menu.language_code = 'ENG'

)

select * from decoded_item_status
