-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per supplier account.
with source as (
    select * from {{ source('sage_x3', 'BPSUPPLIER') }}
),

cleaned as (

    select
        nullif(trim("BPSNUM_0"), '') as supplier_code,
        nullif(trim("BPSNAM_0"), '') as supplier_name,
        nullif(trim("CUR_0"), '') as currency_code,
        nullif(trim("PTE_0"), '') as payment_term_code,
        cast("LTI_0" as bigint) as lead_time_days,
        nullif(trim("ACCCOD_0"), '') as accounting_code,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

)

select * from cleaned
