-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per business partner and address code.
with source as (
    select * from {{ source('sage_x3', 'BPADDRESS') }}
),

cleaned as (

    select
        cast("BPATYP_0" as bigint) as partner_type_code,
        nullif(trim("BPANUM_0"), '') as partner_code,
        nullif(trim("BPAADD_0"), '') as address_code,
        nullif(trim("BPADES_0"), '') as address_description,
        nullif(trim("ADDLIG_0"), '') as address_line_1,
        nullif(trim("ADDLIG_1"), '') as address_line_2,
        nullif(trim("CTY_0"), '') as city,
        nullif(trim("SAT_0"), '') as state_province,
        nullif(trim("POSCOD_0"), '') as postal_code,
        nullif(trim("CRY_0"), '') as country_code,
        nullif(trim("TEL_0"), '') as phone

    from source

)

select * from cleaned
