-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per goods receipt header.
with source as (
    select * from {{ source('sage_x3', 'PRECEIPT') }}
),

cleaned as (

    select
        nullif(trim("PTHNUM_0"), '') as receipt_number,
        nullif(trim("PTHFCY_0"), '') as receipt_site_code,
        nullif(trim("BPSNUM_0"), '') as supplier_code,
        nullif(trim("POHNUM_0"), '') as purchase_order_number,
        nullif("RCPDAT_0", date '1753-01-01') as receipt_date,
        cast("PTHTYP_0" as bigint) as receipt_type_code,
        nullif(trim("CREUSR_0"), '') as received_by,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

)

select * from cleaned
