-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per legal entity.
with source as (
    select * from {{ source('sage_x3', 'COMPANY') }}
),

cleaned as (

    select
        nullif(trim("CPY_0"), '') as company_code,
        nullif(trim("CPYNAM_0"), '') as company_name,
        nullif(trim("CRY_0"), '') as country_code,
        nullif(trim("LEG_0"), '') as legislation_code,
        cast("CPYLOG_0" as bigint) as is_logistics_flag

    from source

)

select * from cleaned
