-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per inventory count session.
with source as (
    select * from {{ source('sage_x3', 'STOCOUNT') }}
),

cleaned as (

    select
        nullif(trim("SESNUM_0"), '') as count_session_number,
        nullif(trim("STOFCY_0"), '') as site_code,
        nullif("CNTDAT_0", date '1753-01-01') as count_date,
        cast("CNTTYP_0" as bigint) as count_type_code,
        cast("SESSTA_0" as bigint) as session_status_code,
        nullif(trim("CREUSR_0"), '') as counted_by,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

),

decoded_count_type as (

    select
        base.*,
        menu.menu_label as count_type

    from cleaned as base
    left join {{ ref('stg_sage_x3__aplstd') }} as menu
        on menu.menu_chapter = 730
        and menu.menu_code = base.count_type_code
        and menu.language_code = 'ENG'

),

decoded_session_status as (

    select
        base.*,
        menu.menu_label as session_status

    from decoded_count_type as base
    left join {{ ref('stg_sage_x3__aplstd') }} as menu
        on menu.menu_chapter = 740
        and menu.menu_code = base.session_status_code
        and menu.language_code = 'ENG'

)

select * from decoded_session_status
