-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per customer account.
with source as (
    select * from {{ source('sage_x3', 'BPCUSTOMER') }}
),

cleaned as (

    select
        nullif(trim("BPCNUM_0"), '') as customer_code,
        nullif(trim("BPCNAM_0"), '') as customer_name,
        nullif(trim("BPCGRU_0"), '') as customer_group_code,
        nullif(trim("CUR_0"), '') as currency_code,
        nullif(trim("PTE_0"), '') as payment_term_code,
        cast("BPCSNC_0" as decimal(18, 4)) as credit_limit_amount,
        cast("OSTCTL_0" as bigint) as credit_control_code,
        nullif(trim("ACCCOD_0"), '') as accounting_code,
        nullif(trim("REP_0"), '') as primary_rep_code,
        nullif(trim("REP_1"), '') as secondary_rep_code,
        nullif("CREDAT_0", date '1753-01-01') as created_date,
        nullif("UPDDAT_0", date '1753-01-01') as updated_date,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

)

select * from cleaned
