-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per customer return line.
with source as (
    select * from {{ source('sage_x3', 'SRETURND') }}
),

cleaned as (

    select
        nullif(trim("SRHNUM_0"), '') as return_number,
        cast("SRDLIN_0" as bigint) as return_line_number,
        nullif(trim("ITMREF_0"), '') as item_code,
        cast("QTY_0" as decimal(18, 4)) as returned_qty,
        cast("NETPRI_0" as decimal(18, 4)) as net_unit_price,
        cast("AMTNOTLIN_0" as decimal(18, 4)) as line_net_amount,
        nullif(trim("SOHNUM_0"), '') as sales_order_number,
        cast("SOPLIN_0" as bigint) as sales_order_line_number,
        nullif(trim("STOFCY_0"), '') as site_code,
        cast("RTNREN_0" as bigint) as return_reason_code

    from source

),

decoded_return_reason as (

    select
        base.*,
        menu.menu_label as return_reason

    from cleaned as base
    left join {{ ref('stg_sage_x3__aplstd') }} as menu
        on menu.menu_chapter = 720
        and menu.menu_code = base.return_reason_code
        and menu.language_code = 'ENG'

)

select * from decoded_return_reason
