-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per local menu chapter, code and language.
with source as (
    select * from {{ source('sage_x3', 'APLSTD') }}
),

cleaned as (

    select
        cast("CHAPTER_0" as bigint) as menu_chapter,
        cast("CODE_0" as bigint) as menu_code,
        nullif(trim("LANNUM_0"), '') as language_code,
        nullif(trim("TEXTE_0"), '') as menu_label

    from source

)

select * from cleaned
