-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per GL journal line.
with source as (
    select * from {{ source('sage_x3', 'GACCENTRYD') }}
),

cleaned as (

    select
        nullif(trim("NUM_0"), '') as journal_entry_number,
        cast("LIN_0" as bigint) as journal_line_number,
        nullif(trim("ACC_0"), '') as gl_account_code,
        cast("SNS_0" as bigint) as debit_credit_sign,
        cast("AMTCUR_0" as decimal(18, 4)) as amount_document_currency,
        cast("AMTLOC_0" as decimal(18, 4)) as amount_company_currency,
        nullif(trim("BPR_0"), '') as partner_code,
        nullif(trim("CPY_0"), '') as company_code,
        nullif(trim("FCY_0"), '') as site_code,
        nullif(trim("DSP_0"), '') as dimension_code,
        nullif("ACCDAT_0", date '1753-01-01') as accounting_date

    from source

)

select * from cleaned
