-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per sales invoice line.
with source as (
    select * from {{ source('sage_x3', 'SINVOICED') }}
),

cleaned as (

    select
        nullif(trim("NUM_0"), '') as invoice_number,
        cast("SIDLIN_0" as bigint) as invoice_line_number,
        nullif(trim("ITMREF_0"), '') as item_code,
        nullif(trim("ITMDES1_0"), '') as item_description_at_invoice,
        cast("QTY_0" as decimal(18, 4)) as invoiced_qty,
        cast("NETPRI_0" as decimal(18, 4)) as net_unit_price,
        cast("AMTNOTLIN_0" as decimal(18, 4)) as line_net_amount,
        nullif(trim("SOHNUM_0"), '') as sales_order_number,
        cast("SOPLIN_0" as bigint) as sales_order_line_number,
        nullif(trim("STOFCY_0"), '') as shipping_site_code

    from source

)

select * from cleaned
