-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per site (X3 facility).
with source as (
    select * from {{ source('sage_x3', 'FACILITY') }}
),

cleaned as (

    select
        nullif(trim("FCY_0"), '') as site_code,
        nullif(trim("FCYSHO_0"), '') as site_short_name,
        nullif(trim("FCYNAM_0"), '') as site_name,
        nullif(trim("LEGCPY_0"), '') as company_code,
        nullif(trim("CRY_0"), '') as country_code,
        nullif(trim("CTY_0"), '') as city,
        nullif(trim("SAT_0"), '') as state_province,
        cast("FCYSTO_0" as bigint) as is_stock_site_code,
        cast("FCYSAL_0" as bigint) as is_sales_site_code,
        cast("FCYPUR_0" as bigint) as is_purchase_site_code,
        cast("FCYSTO_0" = 2 as boolean) as is_stock_site,
        cast("FCYSAL_0" = 2 as boolean) as is_sales_site,
        cast("FCYPUR_0" = 2 as boolean) as is_purchase_site

    from source

)

select * from cleaned
