-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per purchase order line.
with source as (
    select * from {{ source('sage_x3', 'PORDERQ') }}
),

cleaned as (

    select
        nullif(trim("POHNUM_0"), '') as purchase_order_number,
        cast("POPLIN_0" as bigint) as purchase_order_line_number,
        cast("POQSEQ_0" as bigint) as purchase_order_line_sequence,
        nullif(trim("ITMREF_0"), '') as item_code,
        nullif(trim("POHFCY_0"), '') as purchase_site_code,
        cast("QTYUOM_0" as decimal(18, 4)) as ordered_qty,
        nullif("EXTRCPDAT_0", date '1753-01-01') as expected_receipt_date,
        cast("RCPQTY_0" as decimal(18, 4)) as received_qty,
        nullif("RCPDAT_0", date '1753-01-01') as actual_receipt_date,
        cast("NETPRI_0" as decimal(18, 4)) as net_unit_price,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

)

select * from cleaned
