-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per purchase order header.
with source as (
    select * from {{ source('sage_x3', 'PORDER') }}
),

cleaned as (

    select
        nullif(trim("POHNUM_0"), '') as purchase_order_number,
        nullif(trim("POHFCY_0"), '') as purchase_site_code,
        nullif(trim("BPSNUM_0"), '') as supplier_code,
        nullif("ORDDAT_0", date '1753-01-01') as order_date,
        cast("ORDSTA_0" as bigint) as order_status_code,
        nullif(trim("CUR_0"), '') as currency_code,
        nullif(trim("CREUSR_0"), '') as created_by,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

),

decoded_order_status as (

    select
        base.*,
        menu.menu_label as order_status

    from cleaned as base
    left join {{ ref('stg_sage_x3__aplstd') }} as menu
        on menu.menu_chapter = 415
        and menu.menu_code = base.order_status_code
        and menu.language_code = 'ENG'

)

select * from decoded_order_status
