-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per sales invoice header.
with source as (
    select * from {{ source('sage_x3', 'SINVOICEV') }}
),

cleaned as (

    select
        nullif(trim("NUM_0"), '') as invoice_number,
        nullif(trim("SIVTYP_0"), '') as invoice_type_code,
        nullif("INVDAT_0", date '1753-01-01') as invoice_date,
        nullif(trim("BPR_0"), '') as customer_code,
        nullif(trim("SALFCY_0"), '') as sales_site_code,
        nullif(trim("CUR_0"), '') as currency_code,
        cast("AMTNOTLIN_0" as decimal(18, 4)) as invoice_net_amount,
        cast("AMTTAXLIN_0" as decimal(18, 4)) as invoice_tax_amount,
        cast("AMTATILIN_0" as decimal(18, 4)) as invoice_gross_amount,
        cast("INVSTA_0" as bigint) as invoice_status_code,
        nullif("PAYDAT_0", date '1753-01-01') as payment_date,
        nullif("ACCDAT_0", date '1753-01-01') as accounting_date,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

)

select * from cleaned
