-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per sales order header.
with source as (
    select * from {{ source('sage_x3', 'SORDER') }}
),

cleaned as (

    select
        nullif(trim("SOHNUM_0"), '') as sales_order_number,
        nullif(trim("SALFCY_0"), '') as sales_site_code,
        nullif(trim("STOFCY_0"), '') as shipping_site_code,
        nullif(trim("BPCORD_0"), '') as ordering_customer_code,
        nullif(trim("BPCINV_0"), '') as invoicing_customer_code,
        nullif("ORDDAT_0", date '1753-01-01') as order_date,
        nullif("SHIDAT_0", date '1753-01-01') as shipment_date,
        nullif(trim("CUR_0"), '') as currency_code,
        cast("ORDSTA_0" as bigint) as order_status_code,
        nullif(trim("REP_0"), '') as primary_rep_code,
        nullif(trim("REP_1"), '') as secondary_rep_code,
        cast("TOTLINAMT_0" as decimal(18, 4)) as order_total_amount,
        cast("ORDINVSTA_0" as bigint) as invoicing_status_code,
        nullif(trim("CREUSR_0"), '') as created_by,
        nullif("CREDAT_0", date '1753-01-01') as created_date,
        nullif("UPDDAT_0", date '1753-01-01') as updated_date,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

),

decoded_order_status as (

    select
        base.*,
        menu.menu_label as order_status

    from cleaned as base
    left join {{ ref('stg_sage_x3__aplstd') }} as menu
        on menu.menu_chapter = 415
        and menu.menu_code = base.order_status_code
        and menu.language_code = 'ENG'

)

select * from decoded_order_status
