-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per sales order line (price side).
with source as (
    select * from {{ source('sage_x3', 'SORDERP') }}
),

cleaned as (

    select
        nullif(trim("SOHNUM_0"), '') as sales_order_number,
        cast("SOPLIN_0" as bigint) as sales_order_line_number,
        cast("SOPSEQ_0" as bigint) as sales_order_line_sequence,
        nullif(trim("ITMREF_0"), '') as item_code,
        nullif(trim("ITMDES1_0"), '') as item_description_at_order,
        cast("GROPRI_0" as decimal(18, 4)) as gross_unit_price,
        cast("NETPRI_0" as decimal(18, 4)) as net_unit_price,
        cast("DISCRGVAL1_0" as decimal(18, 4)) as discount_amount,
        cast("AMTNOTLIN_0" as decimal(18, 4)) as line_net_amount,
        nullif(trim("VAT1_0"), '') as tax_code,
        cast("UPDTICK_0" as bigint) as update_tick

    from source

)

select * from cleaned
