-- Generated by scripts/generate_process_views.py from seeds/process_metric_map.csv and semantic/metrics/. Do not edit by hand.
-- Process: O2C
--
-- Grain: one row per metric per dimension combination. Long, not wide -
-- the metrics on a dashboard do not share a grain, so a wide row would
-- have to join across incompatible grains and would invent rows.
--
-- Metrics on this dashboard (3):
--   M1  DSO (days-to-pay proxy) (provisional)
--   M2  Return Rate (provisional)
--   M3  Cost Per Order (provisional)

    select
        'O2C' as process_code,
        'M1' as slot,
        1 as display_order,
        'dso_days_to_pay_proxy' as metric_name,
        r.metric_label,
        r.metric_status,
        r.metric_format,
        r.metric_direction,
        m.date_key,
        m.customer_key,
        m.site_code,
        m.item_code,
        cast(null as varchar) as carrier_scac,
        cast(m.numerator as decimal(38, 6)) as numerator,
        cast(m.denominator as decimal(38, 6)) as denominator,
        cast(m.metric_value as decimal(38, 6)) as metric_value,
        r.blocked_reason

    from {{ ref('mtr_dso_days_to_pay_proxy') }} as m
    cross join (
        select
            metric_label,
            status    as metric_status,
            format    as metric_format,
            direction as metric_direction,
            nullif(blocked_reason, '') as blocked_reason
        from {{ ref('metric_registry') }}
        where metric_name = 'dso_days_to_pay_proxy'
    ) as r


union all

    select
        'O2C' as process_code,
        'M2' as slot,
        2 as display_order,
        'return_rate' as metric_name,
        r.metric_label,
        r.metric_status,
        r.metric_format,
        r.metric_direction,
        m.date_key,
        m.customer_key,
        m.site_code,
        m.item_code,
        cast(null as varchar) as carrier_scac,
        cast(m.numerator as decimal(38, 6)) as numerator,
        cast(m.denominator as decimal(38, 6)) as denominator,
        cast(m.metric_value as decimal(38, 6)) as metric_value,
        r.blocked_reason

    from {{ ref('mtr_return_rate') }} as m
    cross join (
        select
            metric_label,
            status    as metric_status,
            format    as metric_format,
            direction as metric_direction,
            nullif(blocked_reason, '') as blocked_reason
        from {{ ref('metric_registry') }}
        where metric_name = 'return_rate'
    ) as r


union all

    select
        'O2C' as process_code,
        'M3' as slot,
        3 as display_order,
        'cost_per_order' as metric_name,
        r.metric_label,
        r.metric_status,
        r.metric_format,
        r.metric_direction,
        m.date_key,
        m.customer_key,
        m.site_code,
        cast(null as varchar) as item_code,
        cast(null as varchar) as carrier_scac,
        cast(m.numerator as decimal(38, 6)) as numerator,
        cast(m.denominator as decimal(38, 6)) as denominator,
        cast(m.metric_value as decimal(38, 6)) as metric_value,
        r.blocked_reason

    from {{ ref('mtr_cost_per_order') }} as m
    cross join (
        select
            metric_label,
            status    as metric_status,
            format    as metric_format,
            direction as metric_direction,
            nullif(blocked_reason, '') as blocked_reason
        from {{ ref('metric_registry') }}
        where metric_name = 'cost_per_order'
    ) as r
