-- Generated by scripts/generate_process_views.py from seeds/process_metric_map.csv and semantic/metrics/. Do not edit by hand.
-- Process: S2P
--
-- Grain: one row per metric per dimension combination. Long, not wide -
-- the metrics on a dashboard do not share a grain, so a wide row would
-- have to join across incompatible grains and would invent rows.
--
-- Metrics on this dashboard (1):
--   M1  Match Rate (provisional)

    select
        'S2P' as process_code,
        'M1' as slot,
        1 as display_order,
        'match_rate' as metric_name,
        r.metric_label,
        r.metric_status,
        r.metric_format,
        r.metric_direction,
        m.date_key,
        cast(null as varchar) as customer_key,
        m.site_code,
        m.item_code,
        cast(null as varchar) as carrier_scac,
        cast(m.numerator as decimal(38, 6)) as numerator,
        cast(m.denominator as decimal(38, 6)) as denominator,
        cast(m.metric_value as decimal(38, 6)) as metric_value,
        r.blocked_reason

    from {{ ref('mtr_match_rate') }} as m
    cross join (
        select
            metric_label,
            status    as metric_status,
            format    as metric_format,
            direction as metric_direction,
            nullif(blocked_reason, '') as blocked_reason
        from {{ ref('metric_registry') }}
        where metric_name = 'match_rate'
    ) as r
