-- Generated by scripts/generate_process_views.py from seeds/process_metric_map.csv and semantic/metrics/. Do not edit by hand.
-- Process: H2R
--
-- Grain: one row per metric per dimension combination. Long, not wide -
-- the metrics on a dashboard do not share a grain, so a wide row would
-- have to join across incompatible grains and would invent rows.
--
-- This process currently has no metrics mapped to it. The view is
-- deliberately still generated and still typed: an empty dashboard is a
-- valid state the architecture has to tolerate, and a missing view is
-- not the same thing as an empty one.

select
    cast(null as varchar) as process_code,
    cast(null as varchar) as slot,
    cast(null as integer) as display_order,
    cast(null as varchar) as metric_name,
    cast(null as varchar) as metric_label,
    cast(null as varchar) as metric_status,
    cast(null as varchar) as metric_format,
    cast(null as varchar) as metric_direction,
    cast(null as integer) as date_key,
    cast(null as varchar) as customer_key,
    cast(null as varchar) as site_code,
    cast(null as varchar) as item_code,
    cast(null as varchar) as carrier_scac,
    cast(null as decimal(38, 6)) as numerator,
    cast(null as decimal(38, 6)) as denominator,
    cast(null as decimal(38, 6)) as metric_value,
    cast(null as varchar) as blocked_reason
where false
