-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per Netstock supplier.
with source as (
    select * from {{ source('netstock', 'supplier') }}
),

cleaned as (

    select
        nullif(trim("supplier_code"), '') as supplier_code,
        nullif(trim("supplier_name"), '') as supplier_name,
        cast("lead_time_days" as bigint) as lead_time_days,
        cast("min_order_value" as decimal(18, 4)) as min_order_value,
        nullif(trim("source_system"), '') as source_system

    from source

)

select * from cleaned
