-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per item, location and forecast period.
with source as (
    select * from {{ source('netstock', 'forecast') }}
),

cleaned as (

    select
        nullif(trim("item_code"), '') as item_code,
        nullif(trim("location_code"), '') as location_code,
        "period_start" as period_start_date,
        nullif(trim("period_type"), '') as period_type,
        cast("forecast_qty" as decimal(18, 4)) as forecast_qty,
        nullif(trim("forecast_method"), '') as forecast_method,
        "generated_at" as generated_date

    from source

)

select * from cleaned
