-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per item and location.
with source as (
    select * from {{ source('netstock', 'item_location') }}
),

cleaned as (

    select
        nullif(trim("item_code"), '') as item_code,
        nullif(trim("location_code"), '') as location_code,
        nullif(trim("description"), '') as item_description,
        nullif(trim("abc_class"), '') as abc_class,
        nullif(trim("xyz_class"), '') as xyz_class,
        nullif(trim("policy"), '') as replenishment_policy,
        cast("lead_time_days" as bigint) as lead_time_days,
        cast("safety_stock_qty" as decimal(18, 4)) as safety_stock_qty,
        cast("reorder_point_qty" as decimal(18, 4)) as reorder_point_qty,
        cast("min_order_qty" as decimal(18, 4)) as min_order_qty,
        nullif(trim("supplier_code"), '') as supplier_code,
        cast("on_hand_qty" as decimal(18, 4)) as on_hand_qty,
        cast("on_order_qty" as decimal(18, 4)) as on_order_qty,
        cast("excess_value" as decimal(18, 4)) as excess_value,
        nullif(trim("stockout_risk"), '') as stockout_risk,
        "last_sync_at" as last_sync_date

    from source

)

select * from cleaned
