-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per recommendation.
with source as (
    select * from {{ source('netstock', 'replenishment_recommendation') }}
),

cleaned as (

    select
        nullif(trim("recommendation_id"), '') as recommendation_id,
        nullif(trim("item_code"), '') as item_code,
        nullif(trim("location_code"), '') as location_code,
        cast("recommended_qty" as decimal(18, 4)) as recommended_qty,
        "recommended_order_date" as recommended_order_date,
        "required_date" as required_date,
        nullif(trim("supplier_code"), '') as supplier_code,
        nullif(trim("status"), '') as status,
        nullif(trim("erp_po_number"), '') as erp_purchase_order_number,
        "generated_at" as generated_date

    from source

)

select * from cleaned
