-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per shipment leg.
with source as (
    select * from {{ source('pangea', 'shipment_leg') }}
),

cleaned as (

    select
        nullif(trim("shipment_id"), '') as shipment_id,
        cast("leg_seq" as bigint) as leg_sequence,
        nullif(trim("mode"), '') as transport_mode,
        nullif(trim("carrier_scac"), '') as carrier_scac,
        nullif(trim("origin"), '') as origin,
        nullif(trim("destination"), '') as destination,
        "depart_ts" as depart_date,
        "arrive_ts" as arrive_date

    from source

)

select * from cleaned
