-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per carrier.
with source as (
    select * from {{ source('pangea', 'carrier') }}
),

cleaned as (

    select
        nullif(trim("scac"), '') as carrier_scac,
        nullif(trim("carrier_name"), '') as carrier_name,
        nullif(trim("mode"), '') as transport_mode

    from source

)

select * from cleaned
