-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per shipment and event sequence.
with source as (
    select * from {{ source('pangea', 'tracking_event') }}
),

cleaned as (

    select
        nullif(trim("shipment_id"), '') as shipment_id,
        cast("event_seq" as bigint) as event_sequence,
        nullif(trim("event_code"), '') as event_code,
        nullif(trim("event_description"), '') as event_description,
        "event_ts" as event_at,
        nullif(trim("event_location"), '') as event_location

    from source

)

select * from cleaned
