-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per shipment.
with source as (
    select * from {{ source('pangea', 'shipment') }}
),

cleaned as (

    select
        nullif(trim("shipment_id"), '') as shipment_id,
        nullif(trim("reference_number"), '') as reference_number,
        nullif(trim("customer_name"), '') as customer_name,
        nullif(trim("carrier_scac"), '') as carrier_scac,
        nullif(trim("service_level"), '') as service_level,
        nullif(trim("mode"), '') as transport_mode,
        nullif(trim("origin_site_code"), '') as origin_site_code,
        nullif(trim("dest_city"), '') as destination_city,
        nullif(trim("dest_state"), '') as destination_state,
        nullif(trim("dest_postal"), '') as destination_postal_code,
        nullif(trim("dest_country"), '') as destination_country,
        "ship_date" as ship_date,
        "estimated_delivery_date" as carrier_promised_delivery_date,
        "delivered_date" as delivered_date,
        nullif(trim("status"), '') as shipment_status,
        cast("weight_lb" as decimal(18, 4)) as weight_lb,
        cast("piece_count" as bigint) as piece_count,
        cast("total_cost_usd" as decimal(18, 4)) as header_cost_usd,
        "created_at" as created_date

    from source

)

select * from cleaned
