-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per shipment and charge code.
with source as (
    select * from {{ source('pangea', 'charge') }}
),

cleaned as (

    select
        nullif(trim("shipment_id"), '') as shipment_id,
        nullif(trim("charge_code"), '') as charge_code,
        cast("amount_usd" as decimal(18, 4)) as charge_amount_usd,
        nullif(trim("currency"), '') as currency_code

    from source

)

select * from cleaned
