-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per HubSpot deal.
with source as (
    select * from {{ source('hubspot', 'deal') }}
),

cleaned as (

    select
        nullif(trim("id"), '') as deal_id,
        nullif(trim("dealname"), '') as deal_name,
        try_cast(nullif(trim("amount"), '') as double) as deal_amount,
        nullif(trim("dealstage"), '') as deal_stage_id,
        nullif(trim("pipeline"), '') as pipeline_id,
        "closedate" as close_date,
        "createdate" as created_date,
        "hs_lastmodifieddate" as last_modified_date,
        nullif(trim("hubspot_owner_id"), '') as owner_id,
        nullif(trim("dealtype"), '') as deal_type,
        cast("hs_is_closed_won" as boolean) as is_closed_won,
        try_cast(nullif(trim("hs_deal_stage_probability"), '') as double) as stage_probability,
        nullif(trim("erp_order_number"), '') as erp_order_number_raw,
        nullif(trim("associated_company_id"), '') as company_id,
        cast("archived" as boolean) as is_archived

    from source

)

select * from cleaned
