-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per HubSpot engagement.
with source as (
    select * from {{ source('hubspot', 'engagement') }}
),

cleaned as (

    select
        nullif(trim("id"), '') as engagement_id,
        nullif(trim("type"), '') as engagement_type,
        "created_at" as created_date,
        nullif(trim("owner_id"), '') as owner_id,
        nullif(trim("associated_deal_id"), '') as deal_id,
        nullif(trim("associated_company_id"), '') as company_id,
        nullif(trim("body_preview"), '') as body_preview

    from source

)

select * from cleaned
