-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per pipeline and stage.
with source as (
    select * from {{ source('hubspot', 'pipeline_stage') }}
),

cleaned as (

    select
        nullif(trim("pipeline_id"), '') as pipeline_id,
        nullif(trim("pipeline_label"), '') as pipeline_label,
        nullif(trim("stage_id"), '') as deal_stage_id,
        nullif(trim("stage_label"), '') as stage_label,
        cast("display_order" as bigint) as display_order,
        cast("is_closed" as boolean) as is_closed,
        cast("is_closed_won" as boolean) as is_closed_won

    from source

)

select * from cleaned
