-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per deal stage change.
with source as (
    select * from {{ source('hubspot', 'deal_stage_history') }}
),

cleaned as (

    select
        nullif(trim("deal_id"), '') as deal_id,
        nullif(trim("stage"), '') as deal_stage_id,
        "changed_at" as changed_at_date,
        nullif(trim("changed_by_owner_id"), '') as changed_by_owner_id

    from source

)

select * from cleaned
