-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per HubSpot company.
with source as (
    select * from {{ source('hubspot', 'company') }}
),

cleaned as (

    select
        nullif(trim("id"), '') as company_id,
        nullif(trim("name"), '') as company_name,
        nullif(trim("domain"), '') as domain,
        nullif(trim("industry"), '') as industry,
        nullif(trim("country"), '') as country,
        try_cast(nullif(trim("numberofemployees"), '') as double) as employee_count,
        try_cast(nullif(trim("annualrevenue"), '') as double) as annual_revenue,
        nullif(trim("hubspot_owner_id"), '') as owner_id,
        "createdate" as created_date,
        "hs_lastmodifieddate" as last_modified_date,
        cast("archived" as boolean) as is_archived

    from source

)

select * from cleaned
