-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per HubSpot object association.
with source as (
    select * from {{ source('hubspot', 'association') }}
),

cleaned as (

    select
        nullif(trim("from_object_type"), '') as from_object_type,
        nullif(trim("from_id"), '') as from_id,
        nullif(trim("to_object_type"), '') as to_object_type,
        nullif(trim("to_id"), '') as to_id,
        nullif(trim("association_type"), '') as association_type

    from source

)

select * from cleaned
