-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per HubSpot contact.
with source as (
    select * from {{ source('hubspot', 'contact') }}
),

cleaned as (

    select
        nullif(trim("id"), '') as contact_id,
        nullif(trim("email"), '') as email,
        nullif(trim("firstname"), '') as first_name,
        nullif(trim("lastname"), '') as last_name,
        nullif(trim("jobtitle"), '') as job_title,
        nullif(trim("phone"), '') as phone,
        nullif(trim("lifecyclestage"), '') as lifecycle_stage,
        nullif(trim("hs_lead_status"), '') as lead_status,
        nullif(trim("hubspot_owner_id"), '') as owner_id,
        nullif(trim("associatedcompanyid"), '') as company_id,
        "createdate" as created_date,
        "lastmodifieddate" as last_modified_date,
        cast("archived" as boolean) as is_archived

    from source

)

select * from cleaned
