-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per HubSpot owner.
with source as (
    select * from {{ source('hubspot', 'owner') }}
),

cleaned as (

    select
        nullif(trim("id"), '') as owner_id,
        nullif(trim("email"), '') as email,
        nullif(trim("first_name"), '') as first_name,
        nullif(trim("last_name"), '') as last_name,
        nullif(trim("user_id"), '') as user_id,
        cast("archived" as boolean) as is_archived,
        "created_at" as created_date,
        "updated_at" as updated_date

    from source

)

select * from cleaned
