"""Compile the tool-neutral metric registry into every artefact that needs it.

    python scripts/compile_metrics.py            # all targets
    python scripts/compile_metrics.py --check     # validate only
    python scripts/compile_metrics.py sql dax     # named targets

Why this exists
---------------
The high-risk idea in the plan is generating both the warehouse SQL and the
Power BI measures from one metric definition. If a metric is defined twice -
once in SQL and once in DAX - the two will disagree, and the disagreement will
surface in a meeting rather than in a test. This script is the proof that they
need only be defined once.

Targets
-------
sql            models/marts/metrics/mtr_<name>.sql   dbt models, one per active metric
dbt_semantic   models/semantic/_semantic_models.yml  dbt semantic models + metrics
dax            exports/powerbi/measures.dax          DAX measure definitions
tmdl           exports/powerbi/bgr_control_tower.tmdl    TMDL table with those measures
cube           exports/cube/model/cubes/*.yml        Cube schema
json           exports/semantic/metric_registry.json machine-readable contract for agents
docs           docs/metric_catalog.md                the human-readable catalogue

Every target reads the same registry. Adding a tenth target does not touch a
metric definition, and changing a metric definition does not touch a target.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import date

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEMANTIC = os.path.join(ROOT, "semantic")

GENERATED_BANNER = (
    "Generated by scripts/compile_metrics.py from semantic/metrics/. "
    "Do not edit by hand - edit the metric definition and recompile."
)

AGGS = {
    "sum": "sum({expr})",
    "count": "count({expr})",
    "count_distinct": "count(distinct {expr})",
    "avg": "avg({expr})",
    "min": "min({expr})",
    "max": "max({expr})",
}

# Aggregations whose pre-aggregated result can be summed back up to a coarser
# grain. count_distinct cannot: summing distinct counts double-counts anything
# that spans two dimension values.
REAGGREGATABLE = {"sum", "count"}

DAX_AGG = {
    "sum": "SUM({table}[{col}])",
    "count": "COUNTA({table}[{col}])",
    "count_distinct": "DISTINCTCOUNT({table}[{col}])",
    "avg": "AVERAGE({table}[{col}])",
    "min": "MIN({table}[{col}])",
    "max": "MAX({table}[{col}])",
}

CUBE_AGG = {
    "sum": "sum",
    "count": "count",
    "count_distinct": "count_distinct",
    "avg": "avg",
    "min": "min",
    "max": "max",
}

DBT_SEMANTIC_AGG = {
    "sum": "sum",
    "count": "count",
    "count_distinct": "count_distinct",
    "avg": "average",
    "min": "min",
    "max": "max",
}

DAX_FORMAT = {
    "percent": '"0.0%"',
    "currency_usd": '"\\$#,0.00"',
    "days": '"#,0.0"',
    "count": '"#,0"',
}

# --------------------------------------------------------------------------
# Filters (D7)
#
# A filter is a structured triple - column, op, and a value for the comparison
# ops - never a SQL string. Every renderer maps the op to its own dialect from
# the table below, so there is no parsing anywhere and a translation bug is
# unrepresentable rather than merely guarded against.
#
# This replaced a `str.split`-based SQL translator that silently mangled `>=`
# into a column named `days_late >` - the exact class of bug this shape makes
# impossible. It also closes the tool-neutrality claim in open question 5: the
# supported grammar is now declared and finite instead of "whatever the parser
# happens to cope with".
#
# `column` is strictly a column on the base model. A metric needing a
# derivation puts it on the fact, which is already this project's rule.
# --------------------------------------------------------------------------

#: op -> (needs a value, SQL template, DAX template, arity note)
OPS = {
    "is_true":     (False, "{c}",                 "{t}[{c}] = TRUE()"),
    "is_false":    (False, "not {c}",             "{t}[{c}] = FALSE()"),
    "is_null":     (False, "{c} is null",         "ISBLANK({t}[{c}])"),
    "is_not_null": (False, "{c} is not null",     "NOT ISBLANK({t}[{c}])"),
    "eq":          (True,  "{c} = {v}",           "{t}[{c}] = {v}"),
    "ne":          (True,  "{c} <> {v}",          "{t}[{c}] <> {v}"),
    "gt":          (True,  "{c} > {v}",           "{t}[{c}] > {v}"),
    "gte":         (True,  "{c} >= {v}",          "{t}[{c}] >= {v}"),
    "lt":          (True,  "{c} < {v}",           "{t}[{c}] < {v}"),
    "lte":         (True,  "{c} <= {v}",          "{t}[{c}] <= {v}"),
    "in":          (True,  None,                  None),   # rendered specially
}


# --------------------------------------------------------------------------
# P9 - time intelligence
#
# Year-on-year, month-to-date and rolling-12 genuinely belong in DAX: they are
# functions of filter context rather than properties of the metric, and pushing
# them into dbt means materialising a comparison per grain. But they are also
# the first thing a report author hand-writes, and the moment someone types
# "Cost Per Shipment YoY" they pick a date column - which is a measure decision
# made in Power BI.
#
# Emitting them from the registry keeps that on the right side of the rule in
# architecture.md: no measure logic authored in Power BI. The date column comes
# from the metric's own binding in semantic/models.yml, never a guess.
# --------------------------------------------------------------------------

#: name -> (suffix, DAX wrapper around the base measure)
TIME_COMPARISONS = {
    "yoy": ("YoY", "CALCULATE({m}, SAMEPERIODLASTYEAR({d}))"),
    "yoy_pct": ("YoY %", "DIVIDE({m} - CALCULATE({m}, SAMEPERIODLASTYEAR({d})), "
                         "CALCULATE({m}, SAMEPERIODLASTYEAR({d})))"),
    "mtd": ("MTD", "TOTALMTD({m}, {d})"),
    "ytd": ("YTD", "TOTALYTD({m}, {d})"),
    "rolling_12": ("Rolling 12", "CALCULATE({m}, DATESINPERIOD({d}, MAX({d}), -12, MONTH))"),
}


def sql_literal(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def dax_literal(value):
    if isinstance(value, bool):
        return "TRUE()" if value else "FALSE()"
    if isinstance(value, (int, float)):
        return str(value)
    return '"' + str(value).replace('"', '""') + '"'


def filter_sql(spec):
    column, op = spec["column"], spec["op"]
    if op == "in":
        values = ", ".join(sql_literal(v) for v in spec["value"])
        return f"{column} in ({values})"
    return OPS[op][1].format(c=column, v=sql_literal(spec.get("value")))


def filter_dax(table, spec):
    column, op = spec["column"], spec["op"]
    if op == "in":
        clauses = " || ".join(
            f"{table}[{column}] = {dax_literal(v)}" for v in spec["value"])
        return f"FILTER(ALL({table}[{column}]), {clauses})"
    return OPS[op][2].format(t=table, c=column, v=dax_literal(spec.get("value")))


def filters_sql(specs):
    return [filter_sql(f) for f in (specs or [])]


def describe_filter(spec):
    """Human-readable form, for docs and catalogue output."""
    if spec["op"] == "in":
        return f"{spec['column']} in ({', '.join(str(v) for v in spec['value'])})"
    if OPS[spec["op"]][0]:
        return f"{spec['column']} {spec['op']} {spec['value']}"
    return f"{spec['column']} {spec['op'].replace('_', ' ')}"


# --------------------------------------------------------------------------
# Load and validate
# --------------------------------------------------------------------------

class RegistryError(Exception):
    pass


_project_vars: dict = {}


def project_var(name, default=None):
    """Read a var out of dbt_project.yml.

    Every other consumer of these values reads them through dbt. Anything the
    compiler emits should agree with what dbt computes, so it reads the same
    source rather than restating the value.
    """
    if not _project_vars:
        with open(os.path.join(ROOT, "dbt_project.yml")) as fh:
            _project_vars.update(yaml.safe_load(fh).get("vars") or {})
    return _project_vars.get(name, default)


def load_registry():
    dimensions = yaml.safe_load(open(os.path.join(SEMANTIC, "dimensions.yml")))["dimensions"]
    models = yaml.safe_load(open(os.path.join(SEMANTIC, "models.yml")))["models"]
    metrics = []
    metric_dir = os.path.join(SEMANTIC, "metrics")
    for filename in sorted(os.listdir(metric_dir)):
        if not filename.endswith((".yml", ".yaml")):
            continue
        metric = yaml.safe_load(open(os.path.join(metric_dir, filename)))
        metric["_file"] = os.path.join("semantic", "metrics", filename)
        metrics.append(metric)
    return dimensions, models, metrics


# --------------------------------------------------------------------------
# D6 - field consumption
#
# Four renderers walk the same YAML and each is free to interpret or ignore any
# field. Nothing noticed when `filters` reached only the SQL target, and the
# warehouse and the dashboard disagreed about Cost Per Order by 17.3% while the
# generated DAX file headed itself "the dashboard and the database cannot drift
# apart". This table makes silently ignoring a field a build failure.
#
# Adding a semantic field means adding it here and to every target that must
# honour it. That is the point: the compiler refuses to ship a definition it
# cannot fully express.
# --------------------------------------------------------------------------

#: Fields that change what a metric computes. Presentation-only fields
#: (label, format, direction, owner, notes) are deliberately absent.
SEMANTIC_FIELDS = {"base_model", "numerator", "denominator", "filters", "dimensions"}

#: Which of those each computational target actually honours.
#:
#: `dimensions` is honoured differently by target and that difference is real,
#: not a loophole. sql, cube and dbt_semantic name the dimensions in the
#: artefact itself - a GROUP BY, a cube dimension list, a semantic model's
#: entities. dax and tmdl honour it *structurally*: scripts/export_powerbi.py
#: builds a relationship per dimension binding, and a DAX measure is
#: slice-agnostic by construction, so the measure text never mentions them.
#: Both are genuine consumption. What this table forbids is a field that no
#: target honours in any form, which is what happened to `filters`.
CONSUMES = {
    "sql":          {"base_model", "numerator", "denominator", "filters", "dimensions"},
    "dax":          {"base_model", "numerator", "denominator", "filters", "dimensions"},
    "tmdl":         {"base_model", "numerator", "denominator", "filters", "dimensions"},
    "cube":         {"base_model", "numerator", "denominator", "filters", "dimensions"},
    "dbt_semantic": {"base_model", "numerator", "denominator", "filters", "dimensions"},
}

REQUIRED_FIELDS = [
    "name", "label", "status", "description", "grain",
    "base_model", "numerator", "denominator", "filters", "dimensions",
    "owner", "blocked_reason",
]

VALID_STATUS = {"active", "provisional", "blocked"}


def validate(dimensions, models, metrics, verbose=True):
    """Governance lives here. A metric that cannot be validated cannot ship.

    One check degrades rather than failing: column existence needs
    target/catalog.json, which only exists after a `dbt docs generate`. On a
    clean checkout the compiler still runs, but it says so - a silent skip
    would mean "Registry OK" without the strongest check having run.
    """
    errors = []
    seen = {}
    skipped_column_check = False

    for metric in metrics:
        name = metric.get("name", "<unnamed>")
        where = metric["_file"]

        for field in REQUIRED_FIELDS:
            if field not in metric:
                errors.append(f"{where}: missing required field '{field}'")

        if name in seen:
            errors.append(f"{where}: metric '{name}' is already defined in {seen[name]}")
        seen[name] = where

        if metric.get("name") != os.path.splitext(os.path.basename(where))[0]:
            errors.append(f"{where}: filename must match the metric name '{name}'")

        status = metric.get("status")
        if status not in VALID_STATUS:
            errors.append(f"{where}: status '{status}' must be one of {sorted(VALID_STATUS)}")

        if "owner" not in metric:
            errors.append(f"{where}: every metric needs an owner field, even if it is TBD")

        # Every dimension a metric asks for must be conformed, and the base
        # model must know how to reach it. This is the check that stops
        # "customer" quietly meaning three different things.
        for dim in metric.get("dimensions") or []:
            if dim not in dimensions:
                errors.append(f"{where}: dimension '{dim}' is not in semantic/dimensions.yml")

        if status == "blocked":
            if not metric.get("blocked_reason"):
                errors.append(f"{where}: blocked metrics must state blocked_reason")
            if metric.get("base_model") or metric.get("numerator"):
                errors.append(f"{where}: blocked metrics must not carry SQL")
            continue

        base = metric.get("base_model")
        if base not in models:
            errors.append(f"{where}: base_model '{base}' is not in semantic/models.yml")
            continue

        bound = models[base].get("dimensions") or {}
        for dim in metric.get("dimensions") or []:
            if dim not in bound:
                errors.append(
                    f"{where}: base_model '{base}' has no binding for dimension '{dim}' "
                    f"- add it to semantic/models.yml"
                )

        columns = base_model_columns(base)
        referenced = []

        for side in ("numerator", "denominator"):
            spec = metric.get(side)
            if not isinstance(spec, dict):
                errors.append(f"{where}: {side} must be a mapping with agg and column")
                continue
            if spec.get("agg") not in AGGS:
                errors.append(f"{where}: {side}.agg '{spec.get('agg')}' unknown; "
                              f"expected one of {sorted(AGGS)}")
            if spec.get("expression"):
                errors.append(
                    f"{where}: {side}.expression is no longer supported. Rename it to "
                    f"'column' - it must be a bare column on {base}, and any derivation "
                    f"belongs on the fact model."
                )
            if not spec.get("column"):
                errors.append(f"{where}: {side}.column is required")
            else:
                referenced.append((f"{side}.column", spec["column"]))
            errors += filter_errors(spec.get("filter"), f"{where}: {side}.filter",
                                    referenced, f"{side}.filter")

        for index, spec in enumerate(metric.get("filters") or []):
            errors += filter_errors(spec, f"{where}: filters[{index}]",
                                    referenced, f"filters[{index}]")

        # D4 - every column named must exist on the base model. Cheap now that
        # columns are bare references rather than arbitrary SQL. Skipped with a
        # note when the warehouse has not been built, so the compiler still
        # runs on a clean checkout.
        if columns is None:
            skipped_column_check = True
        else:
            for label, column in referenced:
                if column not in columns:
                    errors.append(
                        f"{where}: {label} names '{column}', which is not a column on "
                        f"{base}. Available: {', '.join(sorted(columns)[:8])}..."
                    )

        # D6 - a field that no computational target honours is a definition
        # that compiles to something it does not describe.
        set_fields = {f for f in SEMANTIC_FIELDS if metric.get(f)}
        for target, consumed in sorted(CONSUMES.items()):
            dropped = set_fields - consumed
            if dropped:
                errors.append(
                    f"{where}: target '{target}' does not consume {sorted(dropped)} - "
                    f"the compiled artefact would compute something the definition does "
                    f"not describe. Either honour the field in that target or remove it "
                    f"from SEMANTIC_FIELDS."
                )

        for comparison in metric.get("time_comparisons") or []:
            if comparison not in TIME_COMPARISONS:
                errors.append(f"{where}: time_comparison '{comparison}' unknown; "
                              f"expected one of {sorted(TIME_COMPARISONS)}")
            elif "date" not in (models[base].get("dimensions") or {}):
                errors.append(f"{where}: time_comparisons need a date binding, and "
                              f"base_model '{base}' has none in semantic/models.yml")

        if status == "provisional" and not metric.get("provisional_reason"):
            errors.append(f"{where}: provisional metrics must state provisional_reason")

    if skipped_column_check and verbose:
        print(
            "  note: column existence NOT checked - target/catalog.json is "
            "absent.\n"
            "        Run `dbt docs generate` and recompile to enable it. Until "
            "then a\n"
            "        typo in a numerator, denominator or filter column compiles "
            "cleanly\n"
            "        into all six artefacts and fails later, somewhere nobody "
            "is watching.",
            file=sys.stderr,
        )

    if errors:
        raise RegistryError("\n".join("  - " + e for e in errors))


def filter_errors(spec, where, referenced, label):
    """Validate one structured filter. Returns a list of errors."""
    if spec is None:
        return []
    if not isinstance(spec, dict):
        return [f"{where}: a filter must be a mapping with column and op, not a "
                f"SQL string. Supported ops: {', '.join(sorted(OPS))}"]
    errors = []
    if not spec.get("column"):
        errors.append(f"{where}: column is required")
    else:
        referenced.append((label, spec["column"]))
    op = spec.get("op")
    if op not in OPS:
        errors.append(f"{where}: op '{op}' unknown; expected one of {sorted(OPS)}")
        return errors
    needs_value = OPS[op][0]
    has_value = "value" in spec
    if needs_value and not has_value:
        errors.append(f"{where}: op '{op}' requires a value")
    if not needs_value and has_value:
        errors.append(f"{where}: op '{op}' takes no value")
    if op == "in" and has_value and not isinstance(spec["value"], list):
        errors.append(f"{where}: op 'in' requires a list of values")
    return errors


_column_cache: dict = {}


def base_model_columns(model_name):
    """Columns of a mart model, from the dbt catalogue when one exists.

    Returns None when the warehouse has not been built, so validation degrades
    to "cannot check" rather than failing on a clean checkout.
    """
    if not _column_cache:
        catalog = os.path.join(ROOT, "target", "catalog.json")
        if not os.path.exists(catalog):
            _column_cache["_absent"] = True
        else:
            with open(catalog) as fh:
                nodes = json.load(fh).get("nodes", {})
            for node in nodes.values():
                name = node.get("metadata", {}).get("name")
                if name:
                    _column_cache[name] = set(node.get("columns", {}))
    if _column_cache.get("_absent"):
        return None
    return _column_cache.get(model_name)


def agg_sql(spec):
    rendered = AGGS[spec["agg"]].format(expr=spec["column"])
    if spec.get("filter"):
        rendered += f" filter (where {filter_sql(spec['filter'])})"
    return rendered


def is_reaggregatable(metric):
    if metric.get("status") == "blocked":
        return None
    return (metric["numerator"]["agg"] in REAGGREGATABLE
            and metric["denominator"]["agg"] in REAGGREGATABLE)


def active_metrics(metrics):
    return [m for m in metrics if m.get("status") in ("active", "provisional")]


def write(path, content):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w") as fh:
        fh.write(content)
    return path


# --------------------------------------------------------------------------
# Target: sql
# --------------------------------------------------------------------------

def target_sql(dimensions, models, metrics):
    written = []
    for metric in active_metrics(metrics):
        base = metric["base_model"]
        bound = models[base].get("dimensions") or {}
        dims = metric.get("dimensions") or []

        select_lines, group_by = [], []
        for i, dim in enumerate(dims, start=1):
            key = dimensions[dim]["key"]
            column = bound[dim]
            select_lines.append(
                f"        {column}" if column == key else f"        {column} as {key}")
            group_by.append(str(i))

        num = agg_sql(metric["numerator"])
        den = agg_sql(metric["denominator"])
        filters = filters_sql(metric.get("filters"))
        where = ""
        if filters:
            where = "\n    where " + "\n      and ".join(filters)

        select_lines.append(f"        {num} as numerator")
        select_lines.append(f"        {den} as denominator")

        group_clause = f"\n    group by {', '.join(group_by)}" if group_by else ""

        header = [
            f"-- {GENERATED_BANNER}",
            f"-- Metric: {metric['name']} ({metric['label']})",
            f"-- Status: {metric['status']}",
            f"-- Grain of the denominator: {metric['grain']}",
            "--",
            f"-- Numerator:   {num}",
            f"-- Denominator: {den}",
        ]
        if not is_reaggregatable(metric):
            header += [
                "--",
                "-- NOT RE-AGGREGATABLE. The denominator is a distinct count, so",
                "-- summing this model's numerator and denominator across dimension",
                "-- values will over-count. Correct only at the grain below.",
            ]
        header += ["", ""]

        body = (
            "with base as (\n\n"
            f"    select\n" + ",\n".join(select_lines) + "\n\n"
            f"    from {{{{ ref('{base}') }}}}"
            + where
            + group_clause
            + "\n\n),\n\n"
            "final as (\n\n"
            "    select\n"
            + "".join(f"        {dimensions[d]['key']},\n" for d in dims)
            + "        numerator,\n"
            "        denominator,\n"
            # cast so this is not DuckDB-only: two BIGINT sides give integer
            # division in Postgres, SQL Server and Snowflake, where every
            # count-based ratio metric would return 0.
            "        cast(numerator as double) / nullif(denominator, 0) as metric_value,\n"
            f"        '{metric['name']}' as metric_name,\n"
            f"        '{metric['status']}' as metric_status\n\n"
            "    from base\n\n"
            ")\n\n"
            "select * from final\n"
        )
        written.append(write(f"models/marts/metrics/mtr_{metric['name']}.sql",
                             "\n".join(header) + body))

    # A schema file so the generated models are documented in dbt docs too.
    schema = {"version": 2, "models": []}
    for metric in active_metrics(metrics):
        schema["models"].append({
            "name": f"mtr_{metric['name']}",
            "description": (
                f"GENERATED. {metric['label']} ({metric['status']}). "
                f"Grain: {metric['grain']} "
                f"Definition: {metric['_file']}. "
                + ("Re-aggregatable across dimensions."
                   if is_reaggregatable(metric)
                   else "NOT re-aggregatable - the denominator is a distinct count.")
            ),
            "columns": [
                {"name": "numerator", "description": metric["numerator"].get("label", "")},
                {"name": "denominator", "description": metric["denominator"].get("label", "")},
                {"name": "metric_value", "description": "numerator / denominator"},
            ],
        })
    written.append(write("models/marts/metrics/_metrics__models.yml",
                         f"# {GENERATED_BANNER}\n"
                         + yaml.safe_dump(schema, sort_keys=False, width=100)))
    return written


# --------------------------------------------------------------------------
# Target: dbt_semantic
# --------------------------------------------------------------------------

def target_dbt_semantic(dimensions, models, metrics):
    """dbt semantic models + ratio metrics, per the dbt Semantic Layer spec.

    MetricFlow requires every measure to have an aggregation time dimension, so
    a metric whose base model has no date binding cannot be expressed. That is
    a real limitation of the tool, not of the registry: the same metrics
    compile to correct DAX and correct Cube schema. Such metrics are skipped
    here and named in the header of the generated file rather than dropped
    silently.
    """
    def has_time(metric):
        return "date" in (models[metric["base_model"]].get("dimensions") or {})

    supported = [m for m in active_metrics(metrics) if has_time(m)]
    skipped = [m for m in active_metrics(metrics) if not has_time(m)]
    used_models = sorted({m["base_model"] for m in supported})
    semantic_models = []

    for model_name in used_models:
        model = models[model_name]
        bound = model.get("dimensions") or {}
        measures, entities, dims = [], [], []

        for dim, column in bound.items():
            if dim == "date":
                dims.append({"name": "metric_date", "type": "time",
                             "expr": column, "type_params": {"time_granularity": "day"}})
            else:
                entities.append({"name": dim, "type": "foreign", "expr": column})
        for label, column in (model.get("degenerate") or {}).items():
            dims.append({"name": label, "type": "categorical", "expr": column})

        for metric in supported:
            if metric["base_model"] != model_name:
                continue
            # C10: MetricFlow has no metric-level filter, so the metric's
            # filters fold into the CASE guarding every measure alongside the
            # per-side one. Both sides get the same guard, which is what the
            # SQL model's WHERE does.
            metric_conditions = filters_sql(metric.get("filters"))
            for side in ("numerator", "denominator"):
                spec = metric[side]
                conditions = list(metric_conditions)
                if spec.get("filter"):
                    conditions.append(filter_sql(spec["filter"]))
                expr = spec["column"]
                if conditions:
                    expr = f"case when {' and '.join(conditions)} then {expr} end"
                measures.append({
                    "name": f"{metric['name']}_{side}",
                    "agg": DBT_SEMANTIC_AGG[spec["agg"]],
                    "expr": expr,
                    "description": spec.get("label", f"{metric['label']} {side}"),
                })

        semantic_models.append({
            "name": f"sm_{model_name}",
            "description": " ".join((model.get("description") or "").split()),
            "model": f"ref('{model_name}')",
            # Several facts have composite grains, so a virtual primary entity
            # is the honest declaration - naming one column would imply a
            # uniqueness that does not hold.
            "primary_entity": model_name,
            "defaults": {"agg_time_dimension": "metric_date"} if any(
                d["name"] == "metric_date" for d in dims) else {},
            "entities": entities,
            "dimensions": dims,
            "measures": measures,
        })

    metric_defs = []
    for metric in supported:
        # A dbt ratio metric references two *metrics*, not two measures, so
        # each side needs a simple metric wrapping its measure first.
        for side in ("numerator", "denominator"):
            metric_defs.append({
                "name": f"{metric['name']}_{side}",
                "label": f"{metric['label']} - {side}",
                "description": metric[side].get("label", f"{metric['label']} {side}"),
                "type": "simple",
                "type_params": {"measure": {"name": f"{metric['name']}_{side}"}},
                "meta": {"component_of": metric["name"]},
            })
        metric_defs.append({
            "name": metric["name"],
            "label": metric["label"],
            "description": " ".join(metric["description"].split()),
            "type": "ratio",
            "type_params": {
                "numerator": f"{metric['name']}_numerator",
                "denominator": f"{metric['name']}_denominator",
            },
            "meta": {
                "status": metric["status"],
                "owner": str(metric.get("owner")),
                "definition_file": metric["_file"],
            },
        })

    payload = {"semantic_models": semantic_models, "metrics": metric_defs}

    header = [
        f"# {GENERATED_BANNER}",
        "#",
        "# dbt semantic models and metrics, generated from the tool-neutral",
        "# registry. This is one of several compilation targets - the registry,",
        "# not this file, is the source of truth.",
    ]
    if skipped:
        header += [
            "#",
            "# NOT EXPRESSIBLE IN METRICFLOW, and therefore absent below:",
        ]
        for metric in skipped:
            header.append(
                f"#   {metric['name']} - base model {metric['base_model']} has no date "
                f"dimension, and MetricFlow requires an aggregation time dimension on "
                f"every measure."
            )
        header += [
            "# These metrics compile correctly to DAX and to Cube. The gap is the",
            "# tool's, not the registry's - which is the argument for keeping the",
            "# registry tool-neutral.",
        ]
    header += ["version: 2", ""]

    if skipped:
        print("  note: " + ", ".join(m["name"] for m in skipped)
              + " skipped for dbt_semantic (no time dimension on the base model)")

    return [write("models/semantic/_semantic_models.yml",
                  "\n".join(header) + "\n"
                  + yaml.safe_dump(payload, sort_keys=False, width=100))]


# --------------------------------------------------------------------------
# Target: dax
# --------------------------------------------------------------------------

def dax_measure(metric, models):
    """One DAX expression for a metric, honouring every field it sets.

    The outer CALCULATE carries the metric-level `filters`, so they apply to
    numerator and denominator alike - matching the WHERE semantics of the SQL
    model. Without it the two engines disagree: cost_per_order's
    `filters: [has_order_reference]` was reaching only the SQL target, and the
    dashboard computed $1,830.18 against the warehouse's $1,560.78, a 17.3%
    divergence, because 511 shipments with no order reference were excluded by
    one engine and included by the other.
    """
    base = metric["base_model"]

    def side(spec):
        agg = DAX_AGG[spec["agg"]].format(table=base, col=spec["column"])
        if spec.get("filter"):
            return f"CALCULATE({agg}, {filter_dax(base, spec['filter'])})"
        return agg

    expr = f"DIVIDE({side(metric['numerator'])}, {side(metric['denominator'])})"

    outer = [filter_dax(base, f) for f in (metric.get("filters") or [])]
    if outer:
        expr = f"CALCULATE({expr}, " + ", ".join(outer) + ")"
    return expr


def time_comparison_measures(metric, models):
    """The generated time-intelligence variants (P9), if the metric asks for any."""
    comparisons = metric.get("time_comparisons") or []
    if not comparisons:
        return []
    base = metric["base_model"]
    date_column = (models[base].get("dimensions") or {})["date"]
    # The date the comparison walks is the conformed calendar, reached through
    # the fact's own binding - never a column a report author picked.
    date_ref = "dim_date[date_day]"
    out = []
    for name in comparisons:
        suffix, template = TIME_COMPARISONS[name]
        measure_ref = f"[{metric['label']}]"
        out.append((
            f"{metric['label']} {suffix}",
            template.format(m=measure_ref, d=date_ref),
            name,
            date_column,
        ))
    return out


def comment_block(text, prefix, width=88):
    import textwrap
    return [prefix + line for line in textwrap.wrap(" ".join(text.split()), width)]


def target_dax(dimensions, models, metrics):
    lines = [
        f"// {GENERATED_BANNER}",
        "//",
        "// Paste into a Power BI model, or use the TMDL file next to this one.",
        "// Every measure below is derived from the same YAML that generates the",
        "// warehouse SQL, so the dashboard and the database cannot drift apart.",
        "",
    ]
    for metric in active_metrics(metrics):
        fmt = DAX_FORMAT.get(metric.get("format", ""), '"#,0.00"')
        lines += [
            f"// {metric['label']} - status {metric['status']}, owner {metric.get('owner')}",
        ]
        lines += comment_block(metric["description"], "// ")
        for spec in metric.get("filters") or []:
            lines += comment_block("FILTER: " + describe_filter(spec), "// ")
        for caveat in metric.get("caveats", []):
            lines += comment_block("CAVEAT: " + caveat, "// ")
        lines += [
            f"MEASURE '{metric['base_model']}'[{metric['label']}] = ",
            f"    {dax_measure(metric, models)}",
            f"    FORMAT_STRING = {fmt}",
            "",
        ]
        for label, expression, _, _ in time_comparison_measures(metric, models):
            lines += [
                f"MEASURE '{metric['base_model']}'[{label}] = ",
                f"    {expression}",
                f"    FORMAT_STRING = {fmt}",
                "",
            ]
        if not is_reaggregatable(metric):
            lines.insert(len(lines) - 1,
                         "// NOTE: DISTINCTCOUNT is used rather than a summed "
                         "pre-aggregate, so this measure stays correct at every grain.")
    return [write("exports/powerbi/measures.dax", "\n".join(lines) + "\n")]


# --------------------------------------------------------------------------
# Target: tmdl
# --------------------------------------------------------------------------

def target_tmdl(dimensions, models, metrics):
    by_model = {}
    for metric in active_metrics(metrics):
        by_model.setdefault(metric["base_model"], []).append(metric)

    files = []
    for model_name, model_metrics in sorted(by_model.items()):
        lines = [
            f"/// {GENERATED_BANNER}",
            f"table {model_name}",
            "",
        ]
        for metric in model_metrics:
            fmt = DAX_FORMAT.get(metric.get("format", ""), '"#,0.00"')
            desc = " ".join(metric["description"].split())
            lines += [
                f"\tmeasure '{metric['label']}' = {dax_measure(metric, models)}",
                f"\t\tformatString: {fmt}",
                f"\t\tdisplayFolder: Metrics\\{metric['status'].title()}",
                f"\t\t/// {desc}",
                f"\t\tannotation MetricName = {metric['name']}",
                f"\t\tannotation MetricStatus = {metric['status']}",
                f"\t\tannotation MetricOwner = {metric.get('owner')}",
                f"\t\tannotation DefinitionFile = {metric['_file']}",
                "",
            ]
            for label, expression, kind, _ in time_comparison_measures(metric, models):
                lines += [
                    f"\tmeasure '{label}' = {expression}",
                    f"\t\tformatString: {fmt}",
                    f"\t\tdisplayFolder: Metrics\\Time intelligence",
                    f"\t\tannotation MetricName = {metric['name']}",
                    f"\t\tannotation TimeComparison = {kind}",
                    f"\t\tannotation DefinitionFile = {metric['_file']}",
                    "",
                ]
        files.append(write(f"exports/powerbi/tmdl/{model_name}.tmdl", "\n".join(lines) + "\n"))
    return files


# --------------------------------------------------------------------------
# Target: cube
# --------------------------------------------------------------------------

def target_cube(dimensions, models, metrics):
    by_model = {}
    for metric in active_metrics(metrics):
        by_model.setdefault(metric["base_model"], []).append(metric)

    files = []
    for model_name, model_metrics in sorted(by_model.items()):
        model = models[model_name]
        cube = {
            "name": model_name,
            "sql_table": f"main_core.{model_name}",
            "description": model.get("description", "").strip(),
            "dimensions": [],
            "measures": [],
        }
        for dim, column in (model.get("dimensions") or {}).items():
            cube["dimensions"].append({
                "name": dim,
                "sql": column,
                "type": "time" if dim == "date" else "string",
                "description": dimensions[dim].get("description", "").strip(),
            })
        for label, column in (model.get("degenerate") or {}).items():
            cube["dimensions"].append({"name": label, "sql": column, "type": "string"})

        for metric in model_metrics:
            # C10: metric-level filters apply to both sides, exactly as the
            # WHERE in the SQL model does. Cube has no metric-level filter, so
            # they are folded into every measure's filter list.
            metric_filters = [
                {"sql": f"{{CUBE}}.{filter_sql(f)}"}
                for f in (metric.get("filters") or [])
            ]
            for side in ("numerator", "denominator"):
                spec = metric[side]
                measure = {
                    "name": f"{metric['name']}_{side}",
                    "sql": spec["column"],
                    "type": CUBE_AGG[spec["agg"]],
                }
                side_filters = list(metric_filters)
                if spec.get("filter"):
                    side_filters.append({"sql": f"{{CUBE}}.{filter_sql(spec['filter'])}"})
                if side_filters:
                    measure["filters"] = side_filters
                cube["measures"].append(measure)
            cube["measures"].append({
                "name": metric["name"],
                "sql": (f"{{{metric['name']}_numerator}} / "
                        f"NULLIF({{{metric['name']}_denominator}}, 0)"),
                "type": "number",
                "title": metric["label"],
                "description": " ".join(metric["description"].split()),
                "meta": {"status": metric["status"], "owner": str(metric.get("owner"))},
            })
        files.append(write(f"exports/cube/model/cubes/{model_name}.yml",
                           f"# {GENERATED_BANNER}\n"
                           + yaml.safe_dump({"cubes": [cube]}, sort_keys=False, width=100)))
    return files


# --------------------------------------------------------------------------
# Target: json
# --------------------------------------------------------------------------

def target_json(dimensions, models, metrics):
    """The contract an AI agent reads.

    Deliberately includes the blocked metrics and the caveats. An agent that
    can see "Return Rate exists and is blocked because no returns object
    exists" answers the question correctly; an agent that cannot see it invents
    a number.
    """
    payload = {
        "generated_at": date.today().isoformat(),
        "generated_by": "scripts/compile_metrics.py",
        # Read from the project vars rather than hardcoded: open question 10 is
        # the one that changes this value, and this JSON is what the agent reads.
        "reporting_currency": project_var("reporting_currency", "USD"),
        "dimensions": {
            name: {
                "label": d["label"],
                "model": d["model"],
                "key": d["key"],
                "description": " ".join((d.get("description") or "").split()),
                "attributes": d.get("attributes", []),
            }
            for name, d in dimensions.items()
        },
        "models": {
            name: {
                "label": m.get("label"),
                "grain": m.get("grain"),
                "description": " ".join((m.get("description") or "").split()),
                "dimensions": list((m.get("dimensions") or {}).keys()),
                # The fact column that reaches each dimension. A consumer that
                # has to query the base model directly - which ask_metric.py
                # does for metrics the registry marks non-re-aggregatable -
                # needs the binding, not just the dimension name.
                "dimension_columns": dict(m.get("dimensions") or {}),
                "degenerate_attributes": list((m.get("degenerate") or {}).keys()),
            }
            for name, m in models.items()
        },
        "metrics": [],
    }

    for metric in metrics:
        entry = {
            "name": metric["name"],
            "label": metric["label"],
            "status": metric["status"],
            "is_data_quality": bool(metric.get("is_data_quality")),
            "description": " ".join(metric["description"].split()),
            "grain": metric["grain"],
            "base_model": metric["base_model"],
            "dimensions": metric.get("dimensions") or [],
            "format": metric.get("format"),
            "direction": metric.get("direction"),
            "owner": metric.get("owner"),
            "owner_proposed": metric.get("owner_proposed"),
            "definition_file": metric["_file"],
            "caveats": metric.get("caveats", []),
            "lineage_notes": " ".join((metric.get("lineage_notes") or "").split()),
        }
        if metric["status"] == "blocked":
            entry["blocked_reason"] = " ".join(metric["blocked_reason"].split())
            entry["unblock_requires"] = metric.get("unblock_requires", [])
            entry["queryable"] = False
        else:
            entry["queryable"] = True
            entry["sql_model"] = f"mtr_{metric['name']}"
            entry["numerator"] = metric["numerator"]
            entry["denominator"] = metric["denominator"]
            entry["filters"] = metric.get("filters") or []
            entry["filters_described"] = [
                describe_filter(f) for f in (metric.get("filters") or [])]
            entry["time_comparisons"] = metric.get("time_comparisons") or []
            entry["is_reaggregatable"] = is_reaggregatable(metric)
            if metric.get("provisional_reason"):
                entry["provisional_reason"] = " ".join(metric["provisional_reason"].split())
            if metric.get("companion_metric"):
                entry["companion_metric"] = metric["companion_metric"]
        payload["metrics"].append(entry)

    # The process map is loaded from the seed so the JSON contract answers
    # "which dashboard is this on" without a second lookup.
    map_path = os.path.join(ROOT, "seeds", "process_metric_map.csv")
    process_map = {}
    if os.path.exists(map_path):
        import csv
        with open(map_path) as fh:
            for row in csv.DictReader(fh):
                process_map.setdefault(row["metric_name"], []).append(
                    {"process_code": row["process_code"], "slot": row["slot"]})
    for entry in payload["metrics"]:
        entry["processes"] = process_map.get(entry["name"], [])

    return [write("exports/semantic/metric_registry.json",
                  json.dumps(payload, indent=2) + "\n")]


# --------------------------------------------------------------------------
# Target: docs
# --------------------------------------------------------------------------

def target_docs(dimensions, models, metrics):
    import csv
    map_path = os.path.join(ROOT, "seeds", "process_metric_map.csv")
    process_map = {}
    if os.path.exists(map_path):
        with open(map_path) as fh:
            for row in csv.DictReader(fh):
                process_map.setdefault(row["metric_name"], []).append(
                    f"{row['process_code']} {row['slot']}")

    lines = [
        "# Metric catalogue",
        "",
        f"<!-- {GENERATED_BANNER} -->",
        "",
        "One row per metric definition. A metric appears once here however many",
        "dashboards it lands on - the process column is read from",
        "`seeds/process_metric_map.csv`, not from the definition.",
        "",
        "| Metric | Label | Status | Processes | Owner | Base model | Grain |",
        "|---|---|---|---|---|---|---|",
    ]
    for metric in metrics:
        procs = ", ".join(process_map.get(metric["name"], [])) or "_none_"
        lines.append(
            f"| `{metric['name']}` | {metric['label']} | {metric['status']} | {procs} "
            f"| {metric.get('owner')} | `{metric.get('base_model') or '-'}` "
            f"| {' '.join(metric['grain'].split())} |"
        )

    lines += ["", "---", ""]
    for metric in metrics:
        lines += [
            f"## {metric['label']} (`{metric['name']}`)",
            "",
            f"**Status** {metric['status']}"
            + (f" · **Data quality metric**" if metric.get("is_data_quality") else "")
            + f" · **Owner** {metric.get('owner')}"
            + (f" (proposed: {metric['owner_proposed']})" if metric.get("owner_proposed") else ""),
            "",
            " ".join(metric["description"].split()),
            "",
            f"**Grain** {' '.join(metric['grain'].split())}",
            "",
        ]
        procs = process_map.get(metric["name"], [])
        lines += [
            "**Appears on** " + (", ".join(procs) if procs else
                                 "_no dashboard - registered but unmapped_"),
            "",
        ]
        if metric["status"] == "blocked":
            lines += ["**Blocked** " + " ".join(metric["blocked_reason"].split()), ""]
            if metric.get("unblock_requires"):
                lines += ["**To unblock**", ""]
                lines += [f"- {' '.join(r.split())}" for r in metric["unblock_requires"]]
                lines += [""]
        else:
            lines += [
                f"**Numerator** `{agg_sql(metric['numerator'])}`  ",
                f"**Denominator** `{agg_sql(metric['denominator'])}`  ",
                (f"**Metric filters** "
                 + ", ".join(f"`{describe_filter(f)}`" for f in metric["filters"])
                 + "  ") if metric.get("filters") else "",
                f"**Base model** `{metric['base_model']}`  ",
                f"**Dimensions** {', '.join(metric.get('dimensions') or []) or '_none_'}  ",
                f"**Generated SQL model** `mtr_{metric['name']}`  ",
                f"**Re-aggregatable** {'yes' if is_reaggregatable(metric) else 'no'}",
                "",
            ]
            if metric.get("provisional_reason"):
                lines += ["**Provisional because** "
                          + " ".join(metric["provisional_reason"].split()), ""]
            if metric.get("companion_metric"):
                lines += [f"**Must be published with** `{metric['companion_metric']}`", ""]
        if metric.get("caveats"):
            lines += ["**Caveats**", ""]
            lines += [f"- {' '.join(c.split())}" for c in metric["caveats"]]
            lines += [""]
        if metric.get("lineage_notes"):
            lines += ["**Lineage**", "",
                      " ".join(metric["lineage_notes"].split()), ""]
        lines += [f"_Defined in `{metric['_file']}`._", "", "---", ""]

    return [write("docs/metric_catalog.md", "\n".join(lines))]


def target_seed(dimensions, models, metrics):
    """The registry as a dbt seed.

    Loading it into the warehouse lets dbt enforce referential integrity
    between seeds/process_metric_map.csv and the registry with an ordinary
    relationships test, instead of that check living only in this script. It
    also means Power BI can bind metric metadata - status, owner, caveats -
    without a second source.
    """
    import csv as _csv
    import io

    buf = io.StringIO()
    writer = _csv.writer(buf, lineterminator="\n")
    writer.writerow([
        "metric_name", "metric_label", "status", "is_data_quality", "base_model",
        "grain", "owner", "owner_proposed", "format", "direction",
        "is_reaggregatable", "sql_model", "definition_file", "description",
        "blocked_reason",
    ])
    for metric in metrics:
        blocked = metric["status"] == "blocked"
        writer.writerow([
            metric["name"],
            metric["label"],
            metric["status"],
            str(bool(metric.get("is_data_quality"))).lower(),
            metric.get("base_model") or "",
            " ".join(metric["grain"].split()),
            metric.get("owner") or "",
            metric.get("owner_proposed") or "",
            metric.get("format") or "",
            metric.get("direction") or "",
            "" if blocked else str(bool(is_reaggregatable(metric))).lower(),
            "" if blocked else f"mtr_{metric['name']}",
            metric["_file"],
            " ".join(metric["description"].split()),
            " ".join((metric.get("blocked_reason") or "").split()),
        ])
    return [write("seeds/metric_registry.csv", buf.getvalue())]


TARGETS = {
    "sql": target_sql,
    "seed": target_seed,
    "dbt_semantic": target_dbt_semantic,
    "dax": target_dax,
    "tmdl": target_tmdl,
    "cube": target_cube,
    "json": target_json,
    "docs": target_docs,
}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("targets", nargs="*", default=None,
                        help=f"targets to compile; default all of {sorted(TARGETS)}")
    parser.add_argument("--check", action="store_true",
                        help="validate the registry and exit without writing")
    args = parser.parse_args()

    dimensions, models, metrics = load_registry()
    try:
        validate(dimensions, models, metrics)
    except RegistryError as exc:
        print("Registry validation failed:\n" + str(exc), file=sys.stderr)
        return 1

    counts = {}
    for metric in metrics:
        counts[metric["status"]] = counts.get(metric["status"], 0) + 1
    print(f"Registry OK: {len(metrics)} metrics "
          + ", ".join(f"{n} {s}" for s, n in sorted(counts.items())))

    if args.check:
        return 0

    chosen = args.targets or sorted(TARGETS)
    unknown = [t for t in chosen if t not in TARGETS]
    if unknown:
        print(f"Unknown target(s) {unknown}; available: {sorted(TARGETS)}", file=sys.stderr)
        return 1

    for name in chosen:
        written = TARGETS[name](dimensions, models, metrics)
        print(f"  {name:14} -> {len(written)} file(s)")
        for path in written:
            print(f"                   {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
