"""Generate the nine process presentation views from the seed map.

    python scripts/generate_process_views.py

The nine dashboards are presentation artefacts, not data models. Each one is a
projection of the conformed core through seeds/process_metric_map.csv, so a
metric moving between dashboards is a one-line change to a CSV and nothing
else. Nothing here contains business logic - if it did, the same metric could
mean two things on two dashboards, which is the failure mode the whole design
exists to prevent.

Shape
-----
Each view is long, not wide: one row per metric per dimension combination.

    process_code, slot, display_order,
    metric_name, metric_label, metric_status, metric_format, metric_direction,
    date_key, customer_key, site_code, item_code, carrier_scac,
    numerator, denominator, metric_value, blocked_reason

Long rather than wide because the four metrics on a dashboard do not share a
grain - DSO lives on invoice lines and Cost Per Order on shipments - so a wide
row would require a full outer join across incompatible grains and would
manufacture rows that mean nothing. A scorecard visual consumes this shape
directly.

Blocked metrics emit exactly one row with null measures and a populated
blocked_reason, so the dashboard shows the gap rather than an empty tile that
looks like zero.
"""
import csv
import os
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

BANNER = ("Generated by scripts/generate_process_views.py from "
          "seeds/process_metric_map.csv and semantic/metrics/. "
          "Do not edit by hand.")

# Every conformed dimension a process view exposes. A metric that does not
# support one emits null for it, which is honest: "this metric cannot be sliced
# that way" is different from "this metric is zero there".
DIMENSION_COLUMNS = [
    ("date_key", "integer"),
    ("customer_key", "varchar"),
    ("site_code", "varchar"),
    ("item_code", "varchar"),
    ("carrier_scac", "varchar"),
]

DIMENSION_KEY = {
    "date": "date_key",
    "customer": "customer_key",
    "site": "site_code",
    "item": "item_code",
    "carrier": "carrier_scac",
}


def load():
    metrics = {}
    metric_dir = os.path.join(ROOT, "semantic", "metrics")
    for filename in sorted(os.listdir(metric_dir)):
        if filename.endswith((".yml", ".yaml")):
            metric = yaml.safe_load(open(os.path.join(metric_dir, filename)))
            metrics[metric["name"]] = metric

    processes = []
    with open(os.path.join(ROOT, "seeds", "process.csv")) as fh:
        for row in csv.DictReader(fh):
            processes.append(row)

    mapping = []
    with open(os.path.join(ROOT, "seeds", "process_metric_map.csv")) as fh:
        for row in csv.DictReader(fh):
            mapping.append(row)

    return metrics, processes, mapping


def sql_literal(value):
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def metric_block(entry, metric):
    """One SELECT for one metric on one process.

    Only the mapping - process, slot, order, metric name - is inlined. Every
    descriptive field (label, status, format, direction, blocked_reason) is
    joined from the metric_registry seed, which is compiled from the same YAML
    and already carries a relationships test against this map.

    That copy used to be inlined as escaped SQL literals, blocked_reason as a
    900-character single-quote-escaped string. It is what caused the stale
    mart_s2p.sql incident: a blocked reason was edited, the metric artefacts
    were recompiled, the process views were not, and the view sat in the repo
    describing a definition that no longer existed. regenerate.py --check
    guards that now, but a copy that does not exist needs no guard.
    """
    name = metric["name"]
    registry = (
        "    cross join (\n"
        "        select\n"
        "            metric_label,\n"
        "            status    as metric_status,\n"
        "            format    as metric_format,\n"
        "            direction as metric_direction,\n"
        "            nullif(blocked_reason, '') as blocked_reason\n"
        "        from {{ ref('metric_registry') }}\n"
        f"        where metric_name = {sql_literal(name)}\n"
        "    ) as r\n"
    )

    common = [
        f"        {sql_literal(entry['process_code'])} as process_code",
        f"        {sql_literal(entry['slot'])} as slot",
        f"        {entry['display_order']} as display_order",
        f"        {sql_literal(name)} as metric_name",
        "        r.metric_label",
        "        r.metric_status",
        "        r.metric_format",
        "        r.metric_direction",
    ]

    if metric["status"] == "blocked":
        body = common + [
            f"        cast(null as {t}) as {c}" for c, t in DIMENSION_COLUMNS
        ] + [
            "        cast(null as decimal(38, 6)) as numerator",
            "        cast(null as decimal(38, 6)) as denominator",
            "        cast(null as decimal(38, 6)) as metric_value",
            "        r.blocked_reason",
        ]
        return ("    select\n" + ",\n".join(body)
                + "\n\n    from {{ ref('metric_registry') }} as registry_anchor\n"
                + registry
                + f"    where registry_anchor.metric_name = {sql_literal(name)}\n"), None

    supported = {DIMENSION_KEY[d] for d in (metric.get("dimensions") or [])}
    body = common + [
        (f"        m.{c}" if c in supported else f"        cast(null as {t}) as {c}")
        for c, t in DIMENSION_COLUMNS
    ] + [
        "        cast(m.numerator as decimal(38, 6)) as numerator",
        "        cast(m.denominator as decimal(38, 6)) as denominator",
        "        cast(m.metric_value as decimal(38, 6)) as metric_value",
        "        r.blocked_reason",
    ]
    return ("    select\n" + ",\n".join(body)
            + f"\n\n    from {{{{ ref('mtr_{name}') }}}} as m\n"
            + registry), f"mtr_{name}"


def render(process_code, entries, metrics):
    header = [
        f"-- {BANNER}",
        f"-- Process: {process_code}",
        "--",
        "-- Grain: one row per metric per dimension combination. Long, not wide -",
        "-- the metrics on a dashboard do not share a grain, so a wide row would",
        "-- have to join across incompatible grains and would invent rows.",
    ]

    if not entries:
        header += [
            "--",
            "-- This process currently has no metrics mapped to it. The view is",
            "-- deliberately still generated and still typed: an empty dashboard is a",
            "-- valid state the architecture has to tolerate, and a missing view is",
            "-- not the same thing as an empty one.",
            "",
            "",
        ]
        columns = [
            "    cast(null as varchar) as process_code",
            "    cast(null as varchar) as slot",
            "    cast(null as integer) as display_order",
            "    cast(null as varchar) as metric_name",
            "    cast(null as varchar) as metric_label",
            "    cast(null as varchar) as metric_status",
            "    cast(null as varchar) as metric_format",
            "    cast(null as varchar) as metric_direction",
        ] + [f"    cast(null as {t}) as {c}" for c, t in DIMENSION_COLUMNS] + [
            "    cast(null as decimal(38, 6)) as numerator",
            "    cast(null as decimal(38, 6)) as denominator",
            "    cast(null as decimal(38, 6)) as metric_value",
            "    cast(null as varchar) as blocked_reason",
        ]
        return ("\n".join(header)
                + "select\n" + ",\n".join(columns) + "\nwhere false\n")

    blocks, sources = [], []
    for entry in sorted(entries, key=lambda e: int(e["display_order"])):
        metric = metrics[entry["metric_name"]]
        block, source = metric_block(entry, metric)
        blocks.append(block)
        if source:
            sources.append(source)

    header += [
        "--",
        f"-- Metrics on this dashboard ({len(entries)}):",
    ]
    for entry in sorted(entries, key=lambda e: int(e["display_order"])):
        metric = metrics[entry["metric_name"]]
        header.append(f"--   {entry['slot']}  {metric['label']} ({metric['status']})")
    header += ["", ""]

    return "\n".join(header) + "\n\nunion all\n\n".join(blocks)


def main():
    metrics, processes, mapping = load()

    by_process = {}
    for row in mapping:
        by_process.setdefault(row["process_code"], []).append(row)

    unknown = sorted({r["metric_name"] for r in mapping} - set(metrics))
    if unknown:
        print(f"process_metric_map references unknown metric(s): {unknown}", file=sys.stderr)
        return 1

    out_dir = os.path.join(ROOT, "models", "marts", "process")
    os.makedirs(out_dir, exist_ok=True)

    written = []
    schema = {"version": 2, "models": []}
    for process in processes:
        code = process["process_code"]
        entries = by_process.get(code, [])
        path = os.path.join(out_dir, f"mart_{code.lower()}.sql")
        with open(path, "w") as fh:
            fh.write(render(code, entries, metrics))
        written.append(path)

        if entries:
            listed = ", ".join(
                f"{e['slot']} {metrics[e['metric_name']]['label']}"
                f" ({metrics[e['metric_name']]['status']})"
                for e in sorted(entries, key=lambda e: int(e["display_order"]))
            )
            description = (
                f"GENERATED. Presentation view for {code}. "
                f"Grain: one row per metric per dimension combination. "
                f"Metrics: {listed}."
            )
        else:
            description = (
                f"GENERATED. Presentation view for {code}. "
                f"Grain: one row per metric per dimension combination. "
                f"No metrics are currently mapped to {code}; the view is generated "
                f"and typed but returns no rows. An empty dashboard is a valid state."
            )
        schema["models"].append({"name": f"mart_{code.lower()}", "description": description})

    with open(os.path.join(out_dir, "_process__models.yml"), "w") as fh:
        fh.write(f"# {BANNER}\n" + yaml.safe_dump(schema, sort_keys=False, width=100))

    populated = sum(1 for p in processes if by_process.get(p["process_code"]))
    print(f"wrote {len(written)} process views "
          f"({populated} with metrics, {len(written) - populated} empty)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
