#!/usr/bin/env python
"""Prove the renderers agree, at the levels that can actually be executed.

    python scripts/test_metric_parity.py
    python scripts/test_metric_parity.py --write-dax-gate   # also emit L4 queries

C10 - the warehouse and the dashboard disagreeing about Cost Per Order by
17.3% - was found by reading, not by a test. D6 now stops a field being
silently dropped, but it cannot catch a renderer that consumes a field and
interprets it *differently*: DAX's DISTINCTCOUNT counts BLANK where SQL's
count(distinct) ignores nulls, for instance. Only execution catches that.

Five rungs. Three are reachable without a Power BI runtime:

  L1  field-consumption assert       silently dropped fields    -> D6, in validate()
  L2  structured filters             translation bugs           -> D7, by construction
  L3  mtr_* model vs the base fact   re-aggregation, agg errors -> this script
  L4  execute the DAX and diff       everything else            -> needs Power BI
  L5  one engine (Cube / dbt SL)     drift impossible           -> open question 5

L3 recomputes every active metric two ways - the way a consumer reads the
pre-aggregated model, and directly from the base fact with the declared
aggregation and filters - and asserts they agree. A metric that fails is
telling you it is not re-aggregatable, which the registry should then say.

L4 cannot run here, so the gate is generated instead: one DAX query per metric
with the warehouse's answer beside it, ready for whoever first opens the model.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

import duckdb

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _toolchain import ROOT  # noqa: E402

import compile_metrics as cm  # noqa: E402

WAREHOUSE = os.path.join(ROOT, "warehouse.duckdb")
METRIC_SCHEMA = "main_metrics"
CORE_SCHEMA = "main_core"

#: Ratios of floats do not reconcile bit-for-bit across two different
#: aggregation orders. A cent on a currency metric, a ten-thousandth on a rate.
TOLERANCE = 1e-6

failures: list[str] = []


def check(ok: bool, message: str) -> None:
    print(f"  [{'PASS' if ok else 'FAIL'}] {message}")
    if not ok:
        failures.append(message)


def from_metric_model(con, metric) -> tuple:
    """What a consumer gets by reading the pre-aggregated model."""
    return con.sql(f"""
        select sum(numerator), sum(denominator),
               cast(sum(numerator) as double) / nullif(sum(denominator), 0)
        from {METRIC_SCHEMA}.mtr_{metric['name']}
    """).fetchone()


def from_base_model(con, metric) -> tuple:
    """What the declared aggregation gives when applied to the fact directly."""
    numerator = cm.agg_sql(metric["numerator"])
    denominator = cm.agg_sql(metric["denominator"])
    conditions = cm.filters_sql(metric.get("filters"))
    where = ("where " + " and ".join(conditions)) if conditions else ""
    return con.sql(f"""
        select {numerator}, {denominator},
               cast({numerator} as double) / nullif({denominator}, 0)
        from {CORE_SCHEMA}.{metric['base_model']} {where}
    """).fetchone()


def close(a, b) -> bool:
    if a is None or b is None:
        return a is b
    return abs(float(a) - float(b)) <= max(TOLERANCE, abs(float(b)) * TOLERANCE)


def write_dax_gate(metrics, results) -> list[str]:
    """L4: the queries someone runs in Power BI Desktop's DAX Query View.

    Generated now so the gate exists the day the model is first opened, rather
    than being invented under time pressure at release.
    """
    written = []
    out_dir = os.path.join(ROOT, "exports", "powerbi", "parity")
    os.makedirs(out_dir, exist_ok=True)
    index = [
        "-- Generated by scripts/test_metric_parity.py. Do not edit.",
        "--",
        "-- L4 parity gate. Open the model in Power BI Desktop, paste each query",
        "-- into the DAX Query View, and compare against the expected value.",
        "-- This is the only rung that proves the two engines agree; it is a",
        "-- manual gate of about thirty minutes per release.",
        "--",
        "-- A mismatch is a compiler bug, not a data problem: both engines read",
        "-- the same warehouse. Report the metric and both numbers.",
        "",
    ]
    for metric in metrics:
        expected = results.get(metric["name"])
        if expected is None:
            continue
        body = "\n".join([
            f"// {metric['label']} ({metric['name']})",
            f"// expected from the warehouse: {expected:.6f}",
            f"// tolerance: {TOLERANCE}",
            "EVALUATE",
            f'ROW("value", [{metric["label"]}])',
            "",
        ])
        path = os.path.join(out_dir, f"{metric['name']}.dax")
        with open(path, "w") as fh:
            fh.write(body)
        written.append(os.path.relpath(path, ROOT))
        index.append(f"{metric['name']:34} expected {expected:>16.6f}")
    with open(os.path.join(out_dir, "README.txt"), "w") as fh:
        fh.write("\n".join(index) + "\n")
    written.append(os.path.relpath(os.path.join(out_dir, "README.txt"), ROOT))
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write-dax-gate", action="store_true",
                        help="also emit the L4 queries for Power BI Desktop")
    args = parser.parse_args()

    dimensions, models, metrics = cm.load_registry()
    cm.validate(dimensions, models, metrics)
    active = cm.active_metrics(metrics)

    if not os.path.exists(WAREHOUSE):
        print("warehouse.duckdb not found - run `dbt build` first", file=sys.stderr)
        return 1

    con = duckdb.connect(WAREHOUSE, read_only=True)
    results: dict[str, float] = {}
    try:
        print(f"L3 - pre-aggregated metric model vs the base fact, "
              f"{len(active)} active metric(s)\n")
        for metric in active:
            model = from_metric_model(con, metric)
            base = from_base_model(con, metric)
            results[metric["name"]] = base[2]

            agrees = close(model[2], base[2])
            declared = cm.is_reaggregatable(metric)

            if declared:
                check(agrees,
                      f"{metric['name']:32} {fmt(model[2])} == {fmt(base[2])}")
            else:
                # Declared non-re-aggregatable. It may still agree today - and
                # for cost_per_order it does, because no order in this extract
                # ships twice (open question 12). Agreement is not evidence the
                # declaration is wrong; disagreement would be evidence it is
                # right. Either way, do not fail on it.
                state = "agrees today" if agrees else "diverges, as declared"
                print(f"  [ -- ] {metric['name']:32} not re-aggregatable, {state} "
                      f"({fmt(model[2])} vs {fmt(base[2])})")
    finally:
        con.close()

    if args.write_dax_gate:
        written = write_dax_gate(active, results)
        print(f"\nL4 gate written - {len(written)} file(s) under "
              f"exports/powerbi/parity/")

    print()
    if failures:
        print(f"FAILED: {len(failures)} metric(s) do not reconcile. A metric that "
              f"fails here is\ntelling you it is not re-aggregatable - either set "
              f"that in the registry or\nreshape the metric model.")
        return 1
    print("Every re-aggregatable metric reconciles between the pre-aggregated model\n"
          "and its base fact.")
    return 0


def fmt(value) -> str:
    return "null" if value is None else f"{float(value):,.6f}"


if __name__ == "__main__":
    sys.exit(main())
