#!/usr/bin/env python
"""Rewrite the build-statistics blocks in the docs from the last dbt run.

    python scripts/update_build_stats.py
    python scripts/update_build_stats.py --check

In a project where most of the SQL is generated and there is a CI guard against
stale generated files, a hand-typed model or test count is the one thing that
rots unwatched - and it did: the docs said 207 tests / 203 pass while the build
was producing 210 / 206.

Any doc can opt in by wrapping a paragraph:

    <!-- BUILD-STATS -->
    ...anything...
    <!-- /BUILD-STATS -->

Reads target/manifest.json and target/run_results.json, so it needs a build
first. `--check` fails when the committed text does not match the last build,
which is what wires it into regenerate.py --check.
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _toolchain import ROOT  # noqa: E402

OPEN, CLOSE = "<!-- BUILD-STATS -->", "<!-- /BUILD-STATS -->"


class NotABuild(Exception):
    """run_results.json exists but was written by something other than a build."""


def stats() -> dict:
    manifest_path = os.path.join(ROOT, "target", "manifest.json")
    results_path = os.path.join(ROOT, "target", "run_results.json")
    if not (os.path.exists(manifest_path) and os.path.exists(results_path)):
        raise SystemExit(
            "target/manifest.json or target/run_results.json is missing - "
            "run `dbt build` first."
        )
    with open(manifest_path) as fh:
        manifest = json.load(fh)
    with open(results_path) as fh:
        results = json.load(fh)

    nodes = manifest["nodes"]
    counts: dict = {"model": 0, "test": 0, "seed": 0, "snapshot": 0}
    layers: dict = {}
    for node in nodes.values():
        kind = node["resource_type"]
        if kind in counts:
            counts[kind] += 1
        if kind == "model":
            layer = "/".join(node["fqn"][1:-1]) or "root"
            layers[layer] = layers.get(layer, 0) + 1

    outcome = {"pass": 0, "warn": 0, "error": 0, "fail": 0, "skipped": 0}
    for result in results["results"]:
        status = str(result.get("status", "")).lower()
        outcome[status] = outcome.get(status, 0) + 1

    test_results = [
        r for r in results["results"]
        if nodes.get(r["unique_id"], {}).get("resource_type") == "test"
    ]
    # Every dbt command overwrites run_results.json, so a `dbt snapshot` or
    # `dbt seed` after a build leaves three rows behind that describe nothing.
    # Writing those into the docs as "3 tests pass" would be worse than not
    # writing at all, so the absence of test results is treated as "this was
    # not a build" rather than as a measurement.
    if not test_results:
        raise NotABuild(
            f"target/run_results.json holds {len(results['results'])} result(s) "
            f"and no tests, so it is not from a `dbt build` - most likely a "
            f"`dbt snapshot` or `dbt seed` ran after it and overwrote the file."
        )
    test_outcome = {"pass": 0, "warn": 0, "fail": 0, "error": 0}
    for result in test_results:
        status = str(result.get("status", "")).lower()
        test_outcome[status] = test_outcome.get(status, 0) + 1

    return {
        "models": counts["model"],
        "tests": counts["test"],
        "seeds": counts["seed"],
        "snapshots": counts["snapshot"],
        "sources": len(manifest.get("sources", {})),
        "test_pass": test_outcome["pass"],
        "test_warn": test_outcome["warn"],
        "test_fail": test_outcome["fail"] + test_outcome["error"],
        "layers": layers,
    }


def block(s: dict) -> str:
    return (
        f"{s['models']} models, {s['tests']} data tests, {s['seeds']} seeds, "
        f"{s['snapshots']} snapshots and {s['sources']} sources. "
        f"{s['test_pass']} tests pass, {s['test_warn']} warn with documented "
        f"thresholds, {s['test_fail']} error.\n"
        f"\n"
        f"<sub>Counts generated by `scripts/update_build_stats.py` from the last "
        f"`dbt build`. `regenerate.py --check` fails if they drift.</sub>"
    )


def targets() -> list[str]:
    return sorted(glob.glob(os.path.join(ROOT, "docs", "*.md")))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="fail if any block is out of date")
    args = parser.parse_args()

    try:
        measured = stats()
    except NotABuild as exc:
        # Not an error either way: skipping is correct, and saying so is what
        # stops someone assuming the numbers were checked.
        print(f"  note: build statistics not checked - {exc}", file=sys.stderr)
        return 0

    replacement = f"{OPEN}\n{block(measured)}\n{CLOSE}"

    stale, updated = [], []
    for path in targets():
        with open(path) as fh:
            text = fh.read()
        if OPEN not in text or CLOSE not in text:
            # A doc that only mentions the marker in prose - the review
            # worklist does - has not opted in.
            continue
        start = text.index(OPEN)
        end = text.index(CLOSE) + len(CLOSE)
        current = text[start:end]
        if current == replacement:
            continue
        if args.check:
            stale.append(os.path.relpath(path, ROOT))
            continue
        with open(path, "w") as fh:
            fh.write(text[:start] + replacement + text[end:])
        updated.append(os.path.relpath(path, ROOT))

    if args.check:
        if stale:
            print("Build statistics are stale in:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            print("\nRun `python scripts/update_build_stats.py` after a build.",
                  file=sys.stderr)
            return 1
        print("  ok  build statistics")
        return 0

    print(f"  {measured['models']} models, {measured['tests']} tests "
          f"({measured['test_pass']} pass / {measured['test_warn']} warn / "
          f"{measured['test_fail']} error)")
    for path in updated:
        print(f"  updated {path}")
    if not updated:
        print("  already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
