-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per Paycom employee.
with source as (
    select * from {{ source('paycom', 'employee') }}
),

cleaned as (

    select
        nullif(trim("employee_code"), '') as employee_code,
        nullif(trim("ee_id"), '') as employee_id,
        nullif(trim("legal_first_name"), '') as legal_first_name,
        nullif(trim("legal_last_name"), '') as legal_last_name,
        nullif(trim("preferred_name"), '') as preferred_name,
        nullif(trim("work_email"), '') as work_email,
        try_strptime(nullif(trim("hire_date"), ''), '%m/%d/%Y')::date as hire_date,
        try_strptime(nullif(trim("rehire_date"), ''), '%m/%d/%Y')::date as rehire_date,
        try_strptime(nullif(trim("termination_date"), ''), '%m/%d/%Y')::date as termination_date,
        nullif(trim("employment_status"), '') as employment_status,
        nullif(trim("department_code"), '') as department_code,
        nullif(trim("department_desc"), '') as department_name,
        nullif(trim("location_code"), '') as payroll_location_code,
        nullif(trim("position_title"), '') as position_title,
        nullif(trim("pay_type"), '') as pay_type,
        try_cast(nullif(trim("annual_salary"), '') as decimal(18, 4)) as annual_salary,
        try_cast(nullif(trim("hourly_rate"), '') as decimal(18, 4)) as hourly_rate,
        nullif(trim("manager_ee_id"), '') as manager_employee_id,
        upper(nullif(trim("legal_first_name"), '') || ' ' || nullif(trim("legal_last_name"), '')) as full_name_normalized

    from source

)

select * from cleaned
