-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per payroll code and GL account.
with source as (
    select * from {{ source('paycom', 'gl_mapping') }}
),

cleaned as (

    select
        nullif(trim("code_type"), '') as code_type,
        nullif(trim("code"), '') as payroll_code,
        nullif(trim("description"), '') as code_description,
        nullif(trim("gl_account"), '') as gl_account_code

    from source

)

select * from cleaned
