-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per employee and pay period.
with source as (
    select * from {{ source('paycom', 'check') }}
),

cleaned as (

    select
        nullif(trim("check_id"), '') as check_id,
        nullif(trim("employee_code"), '') as employee_code,
        try_strptime(nullif(trim("check_date"), ''), '%m/%d/%Y')::date as check_date,
        try_strptime(nullif(trim("period_start"), ''), '%m/%d/%Y')::date as period_start_date,
        try_strptime(nullif(trim("period_end"), ''), '%m/%d/%Y')::date as period_end_date,
        nullif(trim("check_number"), '') as check_number,
        try_cast(nullif(trim("gross_pay"), '') as decimal(18, 4)) as gross_pay_amount,
        try_cast(nullif(trim("net_pay"), '') as decimal(18, 4)) as net_pay_amount,
        nullif(trim("check_type"), '') as check_type,
        nullif(trim("location_code"), '') as payroll_location_code,
        nullif(trim("department_code"), '') as department_code

    from source

)

select * from cleaned
