-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per check and deduction code.
with source as (
    select * from {{ source('paycom', 'deduction_detail') }}
),

cleaned as (

    select
        nullif(trim("check_id"), '') as check_id,
        nullif(trim("employee_code"), '') as employee_code,
        nullif(trim("deduction_code"), '') as deduction_code,
        try_cast(nullif(trim("ee_amount"), '') as decimal(18, 4)) as employee_amount,
        try_cast(nullif(trim("er_amount"), '') as decimal(18, 4)) as employer_amount

    from source

)

select * from cleaned
