-- Generated by scripts/generate_staging.py. Cleaning only: no business logic.
-- Grain: One row per check and earning code.
with source as (
    select * from {{ source('paycom', 'earning_detail') }}
),

cleaned as (

    select
        nullif(trim("check_id"), '') as check_id,
        nullif(trim("employee_code"), '') as employee_code,
        nullif(trim("earning_code"), '') as earning_code,
        nullif(trim("earning_desc"), '') as earning_description,
        try_cast(nullif(trim("hours"), '') as decimal(18, 4)) as hours,
        try_cast(nullif(trim("amount"), '') as decimal(18, 4)) as earning_amount,
        nullif(trim("labor_allocation_code"), '') as labor_allocation_code

    from source

)

select * from cleaned
