-- Generated by scripts/compile_metrics.py from semantic/metrics/. Do not edit by hand - edit the metric definition and recompile.
-- Metric: customer_unmatched_rate (Unmatched CRM Customers)
-- Status: active
-- Grain of the denominator: One conformed customer.
--
-- Numerator:   sum(crm_company_count) filter (where source_scope = 'crm_only')
-- Denominator: sum(crm_company_count)

with base as (

    select
        sum(crm_company_count) filter (where source_scope = 'crm_only') as numerator,
        sum(crm_company_count) as denominator

    from {{ ref('dim_customer') }}

),

final as (

    select
        numerator,
        denominator,
        cast(numerator as double) / nullif(denominator, 0) as metric_value,
        'customer_unmatched_rate' as metric_name,
        'active' as metric_status

    from base

)

select * from final
