-- Generated by scripts/compile_metrics.py from semantic/metrics/. Do not edit by hand - edit the metric definition and recompile.
-- Metric: on_time_delivery_rate (On-Time Delivery)
-- Status: active
-- Grain of the denominator: One delivered shipment.
--
-- Numerator:   count(shipment_id) filter (where is_on_time_vs_carrier_promise)
-- Denominator: count(shipment_id) filter (where is_on_time_vs_carrier_promise is not null)

with base as (

    select
        ship_date_key as date_key,
        customer_key,
        site_code,
        carrier_scac,
        count(shipment_id) filter (where is_on_time_vs_carrier_promise) as numerator,
        count(shipment_id) filter (where is_on_time_vs_carrier_promise is not null) as denominator

    from {{ ref('fct_shipment') }}
    group by 1, 2, 3, 4

),

final as (

    select
        date_key,
        customer_key,
        site_code,
        carrier_scac,
        numerator,
        denominator,
        cast(numerator as double) / nullif(denominator, 0) as metric_value,
        'on_time_delivery_rate' as metric_name,
        'active' as metric_status

    from base

)

select * from final
