-- Generated by scripts/compile_metrics.py from semantic/metrics/. Do not edit by hand - edit the metric definition and recompile.
-- Metric: cost_per_order (Cost Per Order)
-- Status: provisional
-- Grain of the denominator: One shipped sales order.
--
-- Numerator:   sum(shipment_cost_usd)
-- Denominator: count(distinct sales_order_number)
--
-- NOT RE-AGGREGATABLE. The denominator is a distinct count, so
-- summing this model's numerator and denominator across dimension
-- values will over-count. Correct only at the grain below.

with base as (

    select
        ship_date_key as date_key,
        customer_key,
        site_code,
        sum(shipment_cost_usd) as numerator,
        count(distinct sales_order_number) as denominator

    from {{ ref('fct_shipment') }}
    where has_order_reference
    group by 1, 2, 3

),

final as (

    select
        date_key,
        customer_key,
        site_code,
        numerator,
        denominator,
        cast(numerator as double) / nullif(denominator, 0) as metric_value,
        'cost_per_order' as metric_name,
        'provisional' as metric_status

    from base

)

select * from final
