-- Generated by scripts/compile_metrics.py from semantic/metrics/. Do not edit by hand - edit the metric definition and recompile.
-- Metric: cost_per_shipment (Cost Per Shipment)
-- Status: active
-- Grain of the denominator: One shipment.
--
-- Numerator:   sum(shipment_cost_usd)
-- Denominator: count(shipment_id)

with base as (

    select
        ship_date_key as date_key,
        customer_key,
        site_code,
        carrier_scac,
        sum(shipment_cost_usd) as numerator,
        count(shipment_id) as denominator

    from {{ ref('fct_shipment') }}
    group by 1, 2, 3, 4

),

final as (

    select
        date_key,
        customer_key,
        site_code,
        carrier_scac,
        numerator,
        denominator,
        cast(numerator as double) / nullif(denominator, 0) as metric_value,
        'cost_per_shipment' as metric_name,
        'active' as metric_status

    from base

)

select * from final
