-- Generated by scripts/compile_metrics.py from semantic/metrics/. Do not edit by hand - edit the metric definition and recompile.
-- Metric: unsettled_invoice_rate (Unsettled Invoice Rate)
-- Status: active
-- Grain of the denominator: One sales invoice line.
--
-- Numerator:   count(invoice_number) filter (where is_unsettled)
-- Denominator: count(invoice_number)

with base as (

    select
        invoice_date_key as date_key,
        customer_key,
        site_code,
        count(invoice_number) filter (where is_unsettled) as numerator,
        count(invoice_number) as denominator

    from {{ ref('fct_invoice_line') }}
    group by 1, 2, 3

),

final as (

    select
        date_key,
        customer_key,
        site_code,
        numerator,
        denominator,
        cast(numerator as double) / nullif(denominator, 0) as metric_value,
        'unsettled_invoice_rate' as metric_name,
        'active' as metric_status

    from base

)

select * from final
