-- Generated by scripts/compile_metrics.py from semantic/metrics/. Do not edit by hand - edit the metric definition and recompile.
-- Metric: inventory_accuracy (Inventory Accuracy)
-- Status: provisional
-- Grain of the denominator: One counted stock position.
--
-- Numerator:   count(count_line_number) filter (where is_accurate_position)
-- Denominator: count(count_line_number) filter (where is_accurate_position is not null)

with base as (

    select
        count_date_key as date_key,
        site_code,
        item_code,
        count(count_line_number) filter (where is_accurate_position) as numerator,
        count(count_line_number) filter (where is_accurate_position is not null) as denominator

    from {{ ref('fct_inventory_count_line') }}
    group by 1, 2, 3

),

final as (

    select
        date_key,
        site_code,
        item_code,
        numerator,
        denominator,
        cast(numerator as double) / nullif(denominator, 0) as metric_value,
        'inventory_accuracy' as metric_name,
        'provisional' as metric_status

    from base

)

select * from final
