-- Generated by scripts/compile_metrics.py from semantic/metrics/. Do not edit by hand - edit the metric definition and recompile.
-- Metric: dso_days_to_pay_proxy (DSO (days-to-pay proxy))
-- Status: provisional
-- Grain of the denominator: One settled sales invoice line.
--
-- Numerator:   sum(days_to_pay_settled_only)
-- Denominator: count(days_to_pay_settled_only)

with base as (

    select
        invoice_date_key as date_key,
        customer_key,
        site_code,
        item_code,
        sum(days_to_pay_settled_only) as numerator,
        count(days_to_pay_settled_only) as denominator

    from {{ ref('fct_invoice_line') }}
    group by 1, 2, 3, 4

),

final as (

    select
        date_key,
        customer_key,
        site_code,
        item_code,
        numerator,
        denominator,
        cast(numerator as double) / nullif(denominator, 0) as metric_value,
        'dso_days_to_pay_proxy' as metric_name,
        'provisional' as metric_status

    from base

)

select * from final
