-- Generated by scripts/compile_metrics.py from semantic/metrics/. Do not edit by hand - edit the metric definition and recompile.
-- Metric: order_reference_coverage_rate (Shipment Order Reference Coverage)
-- Status: active
-- Grain of the denominator: One shipment.
--
-- Numerator:   count(shipment_id) filter (where has_order_reference)
-- Denominator: count(shipment_id)

with base as (

    select
        ship_date_key as date_key,
        customer_key,
        site_code,
        carrier_scac,
        count(shipment_id) filter (where has_order_reference) as numerator,
        count(shipment_id) as denominator

    from {{ ref('fct_shipment') }}
    group by 1, 2, 3, 4

),

final as (

    select
        date_key,
        customer_key,
        site_code,
        carrier_scac,
        numerator,
        denominator,
        cast(numerator as double) / nullif(denominator, 0) as metric_value,
        'order_reference_coverage_rate' as metric_name,
        'active' as metric_status

    from base

)

select * from final
