-- Generated by scripts/compile_metrics.py from semantic/metrics/. Do not edit by hand - edit the metric definition and recompile.
-- Metric: match_rate (Match Rate)
-- Status: provisional
-- Grain of the denominator: One supplier invoice line.
--
-- Numerator:   count(supplier_invoice_line_number) filter (where is_three_way_matched)
-- Denominator: count(supplier_invoice_line_number) filter (where is_three_way_matched is not null)

with base as (

    select
        invoice_date_key as date_key,
        site_code,
        item_code,
        count(supplier_invoice_line_number) filter (where is_three_way_matched) as numerator,
        count(supplier_invoice_line_number) filter (where is_three_way_matched is not null) as denominator

    from {{ ref('fct_supplier_invoice_line') }}
    group by 1, 2, 3

),

final as (

    select
        date_key,
        site_code,
        item_code,
        numerator,
        denominator,
        cast(numerator as double) / nullif(denominator, 0) as metric_value,
        'match_rate' as metric_name,
        'provisional' as metric_status

    from base

)

select * from final
