-- Generated by scripts/compile_metrics.py from semantic/metrics/. Do not edit by hand - edit the metric definition and recompile.
-- Metric: return_rate (Return Rate)
-- Status: provisional
-- Grain of the denominator: One sales order line.
--
-- Numerator:   sum(returned_amount_usd)
-- Denominator: sum(invoiced_amount_usd)

with base as (

    select
        order_date_key as date_key,
        customer_key,
        site_code,
        item_code,
        sum(returned_amount_usd) as numerator,
        sum(invoiced_amount_usd) as denominator

    from {{ ref('fct_sales_order_line') }}
    group by 1, 2, 3, 4

),

final as (

    select
        date_key,
        customer_key,
        site_code,
        item_code,
        numerator,
        denominator,
        cast(numerator as double) / nullif(denominator, 0) as metric_value,
        'return_rate' as metric_name,
        'provisional' as metric_status

    from base

)

select * from final
